NAME
  VTK::GeovisCore
LIBRARY_NAME
  vtkGeovisCore
DESCRIPTION
  Core functionality for geospatial visualizations, such as spherical projections.
GROUPS
  Rendering
SPDX_LICENSE_IDENTIFIER
  LicenseRef-BSD-3-Clause-Sandia-USGov
SPDX_COPYRIGHT_TEXT
  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
  Copyright Sandia Corporation
SPDX_CUSTOM_LICENSE_FILE
  LICENSE
SPDX_CUSTOM_LICENSE_NAME
  BSD-3-Clause-Sandia-USGov
LICENSE_FILES
  LICENSE
DEPENDS
  VTK::CommonCore
  VTK::CommonTransforms
  VTK::libproj
TEST_DEPENDS
  VTK::IOImage
  VTK::IOXML
  VTK::InteractionStyle
  VTK::RenderingCore
  VTK::RenderingOpenGL2
  VTK::TestingRendering
  VTK::ViewsInfovis
