vtk_module(vtkInteractionImage
  GROUPS
    Imaging
    Rendering
  DEPENDS
    vtkRenderingCore
    vtkRenderingFreeType
    vtkImagingColor
    vtkInteractionStyle
    vtkInteractionWidgets
  KIT
    vtkInteraction
  )
