vtk_module(vtkRenderingVolumeOpenGLNew
  DEPENDS
    vtkCommonCore
    vtkCommonDataModel
    vtkCommonExecutionModel
    vtkFiltersSources
    vtkRenderingVolume
    vtkRenderingOpenGL
  IMPLEMENTS
    vtkRenderingVolume
  TEST_DEPENDS
    vtkCommonCore
    vtkFiltersModeling
    vtkIOLegacy
    vtkIOXML
    vtkInteractionStyle
    vtkRenderingOpenGL
    vtkRenderingVolumeOpenGLNew
    vtkTestingCore
    vtkTestingRendering
  KIT
    vtkOpenGL
)
