if(ANDROID OR APPLE_IOS OR VTK_OPENGL_USE_GLES) # No GL2PS on mobile
  return()
endif()
vtk_module(vtkIOExportOpenGL2
  IMPLEMENTS
    vtkIOExport
  BACKEND
    OpenGL2
  IMPLEMENTATION_REQUIRED_BY_BACKEND
  TEST_DEPENDS
    vtkRenderingContextOpenGL2
    vtkTestingRendering
    vtkViewsContext2D
  DEPENDS
    vtkIOExport
    vtkRenderingGL2PSOpenGL2
  PRIVATE_DEPENDS
    vtkCommonCore
    vtkCommonDataModel
    vtkImagingCore
    vtkRenderingCore
    vtkgl2ps
)
