/*=========================================================================

  Program:   Visualization Toolkit
  Module:    vtkGraphics.h
  Language:  C++
  Date:      $Date$
  Version:   $Revision$


Copyright (c) 1993-2001 Ken Martin, Will Schroeder, Bill Lorensen 
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

 * Neither name of Ken Martin, Will Schroeder, or Bill Lorensen nor the names
   of any contributors may be used to endorse or promote products derived
   from this software without specific prior written permission.

 * Modified source versions must be plainly marked as such, and must not be
   misrepresented as being the original software.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS ``AS IS''
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHORS OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

=========================================================================*/

#include "vtk3DSImporter.h"
#include "vtkAbstractMapper3D.h"
#include "vtkAbstractPicker.h"
#include "vtkAbstractPropPicker.h"
#include "vtkActor.h"
#include "vtkActorCollection.h"
#include "vtkAppendFilter.h"
#include "vtkAppendPolyData.h"
#include "vtkApproximatingSubdivisionFilter.h"
#include "vtkAssembly.h"
#include "vtkAttributeDataToFieldDataFilter.h"
#include "vtkAxes.h"
#include "vtkBYUReader.h"
#include "vtkBYUWriter.h"
#include "vtkBooleanTexture.h"
#include "vtkBrownianPoints.h"
#include "vtkButterflySubdivisionFilter.h"
#include "vtkCamera.h"
#include "vtkCardinalSpline.h"
#include "vtkCastToConcrete.h"
#include "vtkCellCenters.h"
#include "vtkCellDataToPointData.h"
#include "vtkCellLocator.h"
#include "vtkCellPicker.h"
#include "vtkCleanPolyData.h"
#include "vtkClipPolyData.h"
#include "vtkClipVolume.h"
#include "vtkColorTransferFunction.h"
#include "vtkCone.h"
#include "vtkConeSource.h"
#include "vtkConnectivityFilter.h"
#include "vtkContourFilter.h"
#include "vtkContourGrid.h"
#include "vtkCubeSource.h"
#include "vtkCuller.h"
#include "vtkCullerCollection.h"
#include "vtkCursor3D.h"
#include "vtkCutter.h"
#include "vtkCylinder.h"
#include "vtkCylinderSource.h"
#include "vtkDashedStreamLine.h"
#include "vtkDataObjectReader.h"
#include "vtkDataObjectSource.h"
#include "vtkDataObjectToDataSetFilter.h"
#include "vtkDataObjectWriter.h"
#include "vtkDataReader.h"
#include "vtkDataSetMapper.h"
#include "vtkDataSetReader.h"
#include "vtkDataSetSource.h"
#include "vtkDataSetToDataObjectFilter.h"
#include "vtkDataSetToDataSetFilter.h"
#include "vtkDataSetToPolyDataFilter.h"
#include "vtkDataSetToStructuredGridFilter.h"
#include "vtkDataSetToStructuredPointsFilter.h"
#include "vtkDataSetToUnstructuredGridFilter.h"
#include "vtkDataSetTriangleFilter.h"
#include "vtkDataSetWriter.h"
#include "vtkDataWriter.h"
#include "vtkDecimatePro.h"
#include "vtkDelaunay2D.h"
#include "vtkDelaunay3D.h"
#include "vtkDicer.h"
#include "vtkDirectionEncoder.h"
#include "vtkDiskSource.h"
#include "vtkEdgePoints.h"
#include "vtkElevationFilter.h"
#include "vtkEncodedGradientEstimator.h"
#include "vtkEncodedGradientShader.h"
#include "vtkExporter.h"
#include "vtkExtractEdges.h"
#include "vtkExtractGeometry.h"
#include "vtkExtractGrid.h"
#include "vtkExtractPolyDataGeometry.h"
#include "vtkExtractPolyDataPiece.h"
#include "vtkExtractTensorComponents.h"
#include "vtkExtractUnstructuredGrid.h"
#include "vtkExtractVOI.h"
#include "vtkExtractVectorComponents.h"
#include "vtkFeatureEdges.h"
#include "vtkFieldDataToAttributeDataFilter.h"
#include "vtkFiniteDifferenceGradientEstimator.h"
#include "vtkFollower.h"
#include "vtkFrustumCoverageCuller.h"
#include "vtkGaussianSplatter.h"
#include "vtkGeometryFilter.h"
#include "vtkGhostLevelToScalarFilter.h"
#include "vtkGlyph2D.h"
#include "vtkGlyph3D.h"
#include "vtkGraphicsFactory.h"
#include "vtkHedgeHog.h"
#include "vtkHull.h"
#include "vtkHyperStreamline.h"
#include "vtkIVExporter.h"
#include "vtkIdFilter.h"
#include "vtkImageActor.h"
#include "vtkImplicitBoolean.h"
#include "vtkImplicitDataSet.h"
#include "vtkImplicitModeller.h"
#include "vtkImplicitSelectionLoop.h"
#include "vtkImplicitTextureCoords.h"
#include "vtkImplicitVolume.h"
#include "vtkImplicitWindowFunction.h"
#include "vtkImporter.h"
#include "vtkInteractorStyle.h"
#include "vtkInteractorStyleFlight.h"
#include "vtkInteractorStyleJoystickActor.h"
#include "vtkInteractorStyleJoystickCamera.h"
#include "vtkInteractorStyleSwitch.h"
#include "vtkInteractorStyleTrackball.h"
#include "vtkInteractorStyleTrackballActor.h"
#include "vtkInteractorStyleTrackballCamera.h"
#include "vtkInteractorStyleUser.h"
#include "vtkInterpolateDataSetAttributes.h"
#include "vtkInterpolatingSubdivisionFilter.h"
#include "vtkKochanekSpline.h"
#include "vtkLODActor.h"
#include "vtkLODProp3D.h"
#include "vtkLight.h"
#include "vtkLightCollection.h"
#include "vtkLineSource.h"
#include "vtkLinearExtrusionFilter.h"
#include "vtkLinearSubdivisionFilter.h"
#include "vtkLinkEdgels.h"
#include "vtkLoopSubdivisionFilter.h"
#include "vtkMCubesReader.h"
#include "vtkMCubesWriter.h"
#include "vtkMapper.h"
#include "vtkMapperCollection.h"
#include "vtkMaskPoints.h"
#include "vtkMaskPolyData.h"
#include "vtkMergeDataObjectFilter.h"
#include "vtkMergeFilter.h"
#include "vtkMergePoints.h"
#include "vtkOBBDicer.h"
#include "vtkOBBTree.h"
#include "vtkOBJExporter.h"
#include "vtkOutlineFilter.h"
#include "vtkOutlineSource.h"
#include "vtkPLOT3DReader.h"
#include "vtkPicker.h"
#include "vtkPiecewiseFunction.h"
#include "vtkPlaneSource.h"
#include "vtkPlanes.h"
#include "vtkPointDataToCellData.h"
#include "vtkPointLoad.h"
#include "vtkPointPicker.h"
#include "vtkPointSetSource.h"
#include "vtkPointSetToPointSetFilter.h"
#include "vtkPointSource.h"
#include "vtkPolyDataCollection.h"
#include "vtkPolyDataConnectivityFilter.h"
#include "vtkPolyDataMapper.h"
#include "vtkPolyDataNormals.h"
#include "vtkPolyDataReader.h"
#include "vtkPolyDataStreamer.h"
#include "vtkPolyDataToPolyDataFilter.h"
#include "vtkPolyDataWriter.h"
#include "vtkProbeFilter.h"
#include "vtkProgrammableAttributeDataFilter.h"
#include "vtkProgrammableDataObjectSource.h"
#include "vtkProgrammableFilter.h"
#include "vtkProgrammableGlyphFilter.h"
#include "vtkProgrammableSource.h"
#include "vtkProjectedPolyDataRayBounder.h"
#include "vtkProp3D.h"
#include "vtkProp3DCollection.h"
#include "vtkPropPicker.h"
#include "vtkProperty.h"
#include "vtkQuadricClustering.h"
#include "vtkQuadricDecimation.h"
#include "vtkQuantizePolyDataPoints.h"
#include "vtkRayBounder.h"
#include "vtkRayCaster.h"
#include "vtkRectilinearGridGeometryFilter.h"
#include "vtkRectilinearGridReader.h"
#include "vtkRectilinearGridSource.h"
#include "vtkRectilinearGridToPolyDataFilter.h"
#include "vtkRectilinearGridWriter.h"
#include "vtkRecursiveDividingCubes.h"
#include "vtkRecursiveSphereDirectionEncoder.h"
#include "vtkRemoveGhostCells.h"
#include "vtkRender.h"
#include "vtkRenderWindow.h"
#include "vtkRenderWindowCollection.h"
#include "vtkRenderWindowInteractor.h"
#include "vtkRenderer.h"
#include "vtkRendererCollection.h"
#include "vtkRendererSource.h"
#include "vtkReverseSense.h"
#include "vtkRibbonFilter.h"
#include "vtkRotationalExtrusionFilter.h"
#include "vtkRuledSurfaceFilter.h"
#include "vtkSLCReader.h"
#include "vtkSTLReader.h"
#include "vtkSTLWriter.h"
#include "vtkSampleFunction.h"
#include "vtkScalarTree.h"
#include "vtkSelectPolyData.h"
#include "vtkSelectVisiblePoints.h"
#include "vtkShepardMethod.h"
#include "vtkShrinkFilter.h"
#include "vtkShrinkPolyData.h"
#include "vtkSimpleElevationFilter.h"
#include "vtkSmoothPolyDataFilter.h"
#include "vtkSpatialRepresentationFilter.h"
#include "vtkSphere.h"
#include "vtkSphereSource.h"
#include "vtkSpline.h"
#include "vtkStreamLine.h"
#include "vtkStreamPoints.h"
#include "vtkStreamer.h"
#include "vtkStripper.h"
#include "vtkStructuredGridGeometryFilter.h"
#include "vtkStructuredGridOutlineFilter.h"
#include "vtkStructuredGridReader.h"
#include "vtkStructuredGridSource.h"
#include "vtkStructuredGridToPolyDataFilter.h"
#include "vtkStructuredGridToStructuredGridFilter.h"
#include "vtkStructuredGridWriter.h"
#include "vtkStructuredPointsCollection.h"
#include "vtkStructuredPointsGeometryFilter.h"
#include "vtkStructuredPointsReader.h"
#include "vtkStructuredPointsSource.h"
#include "vtkStructuredPointsToPolyDataFilter.h"
#include "vtkStructuredPointsToStructuredPointsFilter.h"
#include "vtkStructuredPointsToUnstructuredGridFilter.h"
#include "vtkStructuredPointsWriter.h"
#include "vtkSubPixelPositionEdgels.h"
#include "vtkTensorGlyph.h"
#include "vtkTextSource.h"
#include "vtkTexture.h"
#include "vtkTextureMapToCylinder.h"
#include "vtkTextureMapToPlane.h"
#include "vtkTextureMapToSphere.h"
#include "vtkTexturedSphereSource.h"
#include "vtkThreshold.h"
#include "vtkThresholdPoints.h"
#include "vtkThresholdTextureCoords.h"
#include "vtkTransformFilter.h"
#include "vtkTransformPolyDataFilter.h"
#include "vtkTransformTextureCoords.h"
#include "vtkTriangleFilter.h"
#include "vtkTriangularTCoords.h"
#include "vtkTriangularTexture.h"
#include "vtkTubeFilter.h"
#include "vtkUGFacetReader.h"
#include "vtkUnstructuredGridReader.h"
#include "vtkUnstructuredGridSource.h"
#include "vtkUnstructuredGridToUnstructuredGridFilter.h"
#include "vtkUnstructuredGridWriter.h"
#include "vtkVRMLExporter.h"
#include "vtkVectorDot.h"
#include "vtkVectorNorm.h"
#include "vtkVectorText.h"
#include "vtkViewRays.h"
#include "vtkVolume.h"
#include "vtkVolume16Reader.h"
#include "vtkVolumeCollection.h"
#include "vtkVolumeMapper.h"
#include "vtkVolumeProperty.h"
#include "vtkVolumeRayCastCompositeFunction.h"
#include "vtkVolumeRayCastFunction.h"
#include "vtkVolumeRayCastIsosurfaceFunction.h"
#include "vtkVolumeRayCastMIPFunction.h"
#include "vtkVolumeRayCastMapper.h"
#include "vtkVolumeRayCastStructures.h"
#include "vtkVolumeReader.h"
#include "vtkVolumeTextureMapper.h"
#include "vtkVolumeTextureMapper2D.h"
#include "vtkVoxelContoursToSurfaceFilter.h"
#include "vtkVoxelModeller.h"
#include "vtkWarpLens.h"
#include "vtkWarpScalar.h"
#include "vtkWarpTo.h"
#include "vtkWarpVector.h"
#include "vtkWindowedSincPolyDataFilter.h"
#include "vtkWorldPointPicker.h"
#include "vtkWriter.h"
