vtk_module(vtkFiltersSMP
  GROUPS
    StandAlone
  TEST_DEPENDS
    vtkImagingCore
    vtkIOXML
    vtkTestingCore
  KIT
    vtkFilters
  DEPENDS
    vtkCommonCore
    vtkCommonDataModel
    vtkCommonExecutionModel
    vtkCommonMisc
    vtkCommonTransforms
    vtkFiltersCore
    vtkFiltersGeneral
  PRIVATE_DEPENDS
    vtkCommonMath
    vtkCommonSystem
  )