vtk_module(vtkFiltersSMP
  LEGACY 8.1 "The functionality in this module is being replaced with VTK-m integration. Please migrate to that."
  GROUPS
    StandAlone
  TEST_DEPENDS
    vtkImagingCore
    vtkIOXML
    vtkTestingCore
  KIT
    vtkFilters
  DEPENDS
    vtkCommonCore
    vtkCommonDataModel
    vtkCommonExecutionModel
    vtkCommonMisc
    vtkCommonTransforms
    vtkFiltersCore
    vtkFiltersGeneral
  PRIVATE_DEPENDS
    vtkCommonMath
    vtkCommonSystem
  )