NAME
  VTK::InfovisBoost
LIBRARY_NAME
  vtkInfovisBoost
SPDX_LICENSE_IDENTIFIER
  LicenseRef-BSD-3-Clause-Sandia-USGov
SPDX_COPYRIGHT_TEXT
  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
  Copyright Sandia Corporation
SPDX_CUSTOM_LICENSE_FILE
  LICENSE
SPDX_CUSTOM_LICENSE_NAME
  BSD-3-Clause-Sandia-USGov
LICENSE_FILES
  LICENSE
DEPENDS
  VTK::CommonCore
TEST_DEPENDS
  VTK::CommonDataModel
  VTK::TestingCore
  VTK::utf8
EXCLUDE_WRAP
