NAME
  VTK::GUISupportQt
LIBRARY_NAME
  vtkGUISupportQt
DESCRIPTION
  Make VTK render-windows, interactors, and widgets available to Qt applications.
GROUPS
  Qt
SPDX_LICENSE_IDENTIFIER
  LicenseRef-BSD-3-Clause-Sandia-USGov
SPDX_COPYRIGHT_TEXT
  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
  Copyright Sandia Corporation
SPDX_CUSTOM_LICENSE_FILE
  LICENSE
SPDX_CUSTOM_LICENSE_NAME
  BSD-3-Clause-Sandia-USGov
LICENSE_FILES
  LICENSE
DEPENDS
  VTK::CommonCore
  VTK::RenderingCore
  VTK::RenderingOpenGL2
  VTK::InteractionWidgets
PRIVATE_DEPENDS
  VTK::CommonDataModel
  VTK::CommonSystem
  VTK::FiltersExtraction
  VTK::InteractionStyle
TEST_DEPENDS
  VTK::ChartsCore
  VTK::FiltersSources
  VTK::RenderingContextOpenGL2
  VTK::TestingCore
  VTK::TestingRendering
  VTK::ViewsContext2D
EXCLUDE_WRAP
