vtk_module(vtkRenderingContext2D
  GROUPS
    Rendering
  DEPENDS
    vtkCommonDataModel
    vtkCommonMath
    vtkCommonTransforms
    vtkMathText
    vtkRenderingCore
    vtkRenderingOpenGL
    vtkRenderingFreeType
  )
