vtk_module(vtkFiltersGeneral
  GROUPS
    StandAlone
  TEST_DEPENDS
    vtkFiltersFlowPaths
    vtkFiltersModeling
    vtkIOGeometry
    vtkIOLegacy
    vtkIOXML
    vtkImagingMath
    vtkInteractionStyle
    vtkRendering${VTK_RENDERING_BACKEND}
    vtkRenderingAnnotation
    vtkRenderingLabel
    vtkTestingRendering
  KIT
    vtkFilters
  DEPENDS
    vtkCommonCore
    vtkCommonDataModel
    vtkCommonExecutionModel
    vtkCommonMisc
    vtkFiltersCore
  PRIVATE_DEPENDS
    vtkCommonComputationalGeometry
    vtkCommonMath
    vtkCommonSystem
    vtkCommonTransforms
  )