vtk_module(vtkFiltersGeneral
  GROUPS
    StandAlone
  DEPENDS
    vtkCommonComputationalGeometry
    vtkFiltersCore
  TEST_DEPENDS
    vtkIOLegacy
    vtkIOXML
    vtkRenderingOpenGL
    vtkRenderingFreeTypeOpenGL
    vtkRenderingAnnotation
    vtkTestingRendering
  )
