#!/usr/bin/env bash
#=============================================================================
# Copyright 2025 Kitware, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#=============================================================================

set -e

die () {
  echo >&2 "$@"
  exit 1
}

usage () {
  die "Usage: git fetch-mr [--force] [--named <name>] <mr-id>"
}

if [[ "$#" -lt 1 ]]; then
  usage
fi

mr=''
force=''
name=''
while [[ "$#" != 0 ]]; do
  case "$1" in
    -f|--force)
      force='+'
      ;;
    -n|--named)
      shift
      name="$1"
      ;;
    -*) usage ;;
    *)
      [ -z "$mr" ] || usage
      mr="$1"
      ;;
  esac
  shift || usage
done
readonly force
readonly mr

if [ -z "$mr" ]; then
  usage
fi

if [ -z "$name" ]; then
  name="mr-$mr"
fi
readonly name

exec git fetch origin "${force}refs/merge-requests/$mr/head:$name"
