#!/usr/bin/env bash
#=============================================================================
# Copyright 2010-2014 Kitware, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#=============================================================================

. "${BASH_SOURCE%/*}/hooks-config.bash"

# Read all input up front so we can use it and hand it to the chained hook.
stdin="$(cat)" &&

# Chain to project-specific hook.
hooks_chain pre-push "$@"
