#!/usr/bin/env bash
#=============================================================================
# Copyright 2010-2012 Kitware, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#=============================================================================

. "${BASH_SOURCE%/*}/hooks-config.bash"

# Start with project-specific hook.
hooks_start prepare-commit-msg "$@"

# Invoke the Gerrit Change-Id hook here for "git merge" because
# it does not run the normal commit-msg hook.
hooks_GerritId=$(git config --get hooks.GerritId)
case "$hooks_GerritId,$2,$3" in
	true,merge,) "$HOOKS_DIR/gerrit/commit-msg" "$1" ;;
	*) ;;
esac

#-----------------------------------------------------------------------------
# Chain to project-specific hook.
hooks_chain prepare-commit-msg "$@"
