NAME
  VTK::FiltersPython
LIBRARY_NAME
  vtkFiltersPython
CONDITION
  VTK_WRAP_PYTHON
GROUPS
  StandAlone
DESCRIPTION
  Provide a python base class for writing VTK algorithms in python.
SPDX_LICENSE_IDENTIFIER
  BSD-3-Clause
SPDX_COPYRIGHT_TEXT
  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
DEPENDS
  VTK::CommonExecutionModel
PRIVATE_DEPENDS
  VTK::CommonCore
  VTK::WrappingPythonCore
TEST_DEPENDS
  VTK::TestingCore
