vtk_module(vtkChartsCore
  GROUPS
    StandAlone
  TEST_DEPENDS
    vtkTestingCore
    vtkTestingRendering
    vtkViewsContext2D
    vtkRenderingContextOpenGL2
    #vtkIOExport
    vtkIOInfovis
  DEPENDS
    vtkCommonCore
    vtkCommonDataModel
    vtkFiltersGeneral
    vtkRenderingContext2D
    vtkRenderingCore
    vtksys
  PRIVATE_DEPENDS
    vtkCommonColor
    vtkCommonExecutionModel
    vtkCommonTransforms
    vtkInfovisCore
  )
