vtk_module(vtkIOXdmf3
  GROUPS
  TEST_DEPENDS
    vtkFiltersGeneral
    vtkTestingCore
    vtkTestingRendering
  DEPENDS
    vtkCommonCore
    vtkCommonExecutionModel
    vtkIOLegacy
  PRIVATE_DEPENDS
    vtkCommonDataModel
    vtkCommonSystem
    vtkFiltersExtraction
    vtkParallelCore
    vtksys
    vtkxdmf3
  KIT
    vtkParallel
  )
