vtk_module(vtkRenderingContextOpenGL
  DEPENDS
    vtkRenderingOpenGL
  IMPLEMENTS
    vtkRenderingContext2D
  BACKEND
    OpenGL
  IMPLEMENTATION_REQUIRED_BY_BACKEND
  PRIVATE_DEPENDS
    vtkRenderingFreeType
  KIT
    vtkOpenGL
  )
