vtk_module(vtkCommonComputationalGeometry
  GROUPS
    StandAlone
  DEPENDS
    vtkCommonSystem
    vtkCommonMath
    vtkCommonDataModel
  TEST_DEPENDS
    vtkTestingCore
    vtkRendering${VTK_RENDERING_BACKEND}
  KIT
    vtkCommon
  )
