NAME
  VTK::CommonComputationalGeometry
LIBRARY_NAME
  vtkCommonComputationalGeometry
DESCRIPTION
  Parametric splines and curves
KIT
  VTK::Common
GROUPS
  StandAlone
SPDX_LICENSE_IDENTIFIER
  BSD-3-Clause
SPDX_COPYRIGHT_TEXT
  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
DEPENDS
  VTK::CommonCore
  VTK::CommonDataModel
TEST_DEPENDS
  VTK::RenderingOpenGL2
  VTK::TestingCore
  VTK::TestingRendering
