vtk_module(vtkIOGDAL
  TEST_DEPENDS
    vtkTestingCore
    vtkRenderingOpenGL2
    vtkTestingRendering
    vtkInteractionStyle
  KIT
    vtkIO
  DEPENDS
    vtkCommonCore
    vtkCommonExecutionModel
    vtkFiltersCore
    vtkIOImage
  PRIVATE_DEPENDS
    vtkCommonDataModel
)
