NAME
  VTK::IOFides
LIBRARY_NAME
  vtkIOFides
DESCRIPTION
  The base Fides reader library
SPDX_LICENSE_IDENTIFIER
  BSD-3-Clause
SPDX_COPYRIGHT_TEXT
  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
DEPENDS
  VTK::CommonExecutionModel
  VTK::IOCore
OPTIONAL_DEPENDS
  VTK::mpi
  VTK::ParallelMPI
PRIVATE_DEPENDS
  VTK::AcceleratorsVTKmDataModel
  VTK::CommonCore
  VTK::CommonDataModel
  VTK::fides
  VTK::ParallelCore
