NAME
  VTK::FiltersParallelStatistics
LIBRARY_NAME
  vtkFiltersParallelStatistics
KIT
  VTK::Parallel
SPDX_LICENSE_IDENTIFIER
  LicenseRef-BSD-3-Clause-Sandia-USGov
SPDX_COPYRIGHT_TEXT
  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
  Copyright Sandia Corporation
SPDX_CUSTOM_LICENSE_FILE
  LICENSE
SPDX_CUSTOM_LICENSE_NAME
  BSD-3-Clause-Sandia-USGov
LICENSE_FILES
  LICENSE
DEPENDS
  VTK::FiltersStatistics
PRIVATE_DEPENDS
  VTK::CommonCore
  VTK::CommonDataModel
  VTK::CommonSystem
  VTK::ParallelCore
TEST_DEPENDS
  VTK::CommonSystem
  VTK::ParallelMPI
  VTK::TestingCore
