vtk_module(vtkRenderingImage
  GROUPS
    Imaging
    Rendering
  DEPENDS
    vtkImagingCore
    vtkRenderingCore
  TEST_DEPENDS
    vtkTestingCore
    vtkTestingRendering
    vtkRendering${VTK_RENDERING_BACKEND}
    vtkInteractionStyle
    vtkImagingSources
    vtkFiltersModeling
  KIT
    vtkRendering
  )
