vtk_module(vtkIOMINC
  GROUPS
    StandAlone
  TEST_DEPENDS
    vtkRendering${VTK_RENDERING_BACKEND}
  DEPENDS
    vtkCommonCore
    vtkCommonExecutionModel
    vtkIOCore
    vtkIOImage
  PRIVATE_DEPENDS
    vtkCommonDataModel
    vtkCommonMath
    vtkCommonMisc
    vtkCommonTransforms
    vtkFiltersHybrid
    vtkRenderingCore
    vtknetcdf
    vtksys
  )