NAME
  VTK::IOMINC
LIBRARY_NAME
  vtkIOMINC
GROUPS
  StandAlone
LICENSE_FILES
  Copyright.txt
SPDX_LICENSE_IDENTIFIER
  BSD-3-Clause AND MIT
SPDX_COPYRIGHT_TEXT
  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
  Copyright (c) 2006 Atamai, Inc.
  Copyright 1993-2000 Peter Neelin and David MacDonald, McConnell Brain
DEPENDS
  VTK::CommonCore
  VTK::CommonExecutionModel
  VTK::IOCore
  VTK::IOImage
PRIVATE_DEPENDS
  VTK::CommonDataModel
  VTK::CommonMath
  VTK::CommonMisc
  VTK::CommonTransforms
  VTK::FiltersHybrid
  VTK::RenderingCore
  VTK::netcdf
  VTK::vtksys
TEST_DEPENDS
  VTK::InteractionImage
  VTK::RenderingOpenGL2
  VTK::TestingRendering
