NAME
  VTK::CommonTransforms
LIBRARY_NAME
  vtkCommonTransforms
DESCRIPTION
  Linear algebra transformations
KIT
  VTK::Common
GROUPS
  StandAlone
SPDX_LICENSE_IDENTIFIER
  BSD-3-Clause
SPDX_COPYRIGHT_TEXT
  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
DEPENDS
  VTK::CommonCore
  VTK::CommonMath
PRIVATE_DEPENDS
  VTK::vtksys
TEST_DEPENDS
  VTK::InteractionImage
  VTK::RenderingOpenGL2
  VTK::TestingCore
  VTK::TestingRendering
INCLUDE_MARSHAL
