vtk_module(vtkRenderingLICOpenGL2
  TCL_NAME
    vtkRenderingLICOpenGLII
  BACKEND
    OpenGL2
  TEST_DEPENDS
    vtkTestingCore
    vtkTestingRendering
    vtkInteractionStyle
  KIT
    vtkOpenGL
  DEPENDS
    vtkCommonCore
    vtkCommonDataModel
    vtkCommonExecutionModel
    vtkRendering${VTK_RENDERING_BACKEND}
  PRIVATE_DEPENDS
    vtkCommonMath
    vtkCommonSystem
    vtkIOCore
    vtkIOLegacy
    vtkIOXML
    vtkImagingCore
    vtkImagingSources
    vtkRenderingCore
    vtkglew
    vtksys
  )
