NAME
  VTK::DomainsParallelChemistry
LIBRARY_NAME
  vtkDomainsParallelChemistry
DESCRIPTION
  Parallel versions of algorithms used in chemistry
KIT
  VTK::Parallel
GROUPS
  MPI
IMPLEMENTS
  VTK::DomainsChemistry
SPDX_LICENSE_IDENTIFIER
  BSD-3-Clause
SPDX_COPYRIGHT_TEXT
  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
DEPENDS
  VTK::DomainsChemistry
PRIVATE_DEPENDS
  VTK::CommonCore
  VTK::ParallelMPI
  VTK::FiltersParallelMPI
  VTK::mpi
TEST_DEPENDS
  VTK::ParallelMPI
  VTK::TestingCore
