vtk_module(vtkAcceleratorsDax
  DEPENDS
    vtkCommonCore
    vtkCommonDataModel
    vtkCommonExecutionModel
    vtkFiltersCore
    vtkFiltersGeometry
  TEST_DEPENDS
    vtkTestingCore
    vtkTestingRendering
    vtkRenderingVolume
    vtkRenderingVolumeOpenGL
    vtkIOLegacy
    vtkIOXML
    vtkImagingSources
  EXCLUDE_FROM_ALL
  EXCLUDE_FROM_WRAPPING
  EXCLUDE_FROM_WRAP_HIERARCHY
  )
