NAME
  VTK::FiltersImaging
LIBRARY_NAME
  vtkFiltersImaging
DESCRIPTION
  Filters and algorithms for images
KIT
  VTK::Filters
GROUPS
  Imaging
  StandAlone
SPDX_LICENSE_IDENTIFIER
  LicenseRef-BSD-3-Clause-Sandia-USGov
SPDX_COPYRIGHT_TEXT
  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
  Copyright Sandia Corporation
SPDX_CUSTOM_LICENSE_FILE
  LICENSE
SPDX_CUSTOM_LICENSE_NAME
  BSD-3-Clause-Sandia-USGov
LICENSE_FILES
  LICENSE
DEPENDS
  VTK::CommonCore
  VTK::CommonExecutionModel
  VTK::FiltersStatistics
PRIVATE_DEPENDS
  VTK::CommonDataModel
  VTK::CommonSystem
  VTK::ImagingGeneral
