vtk_module(vtkFiltersTracers
  DEPENDS
    vtkCommonExecutionModel
    vtkFiltersAMR
    vtkFiltersGeneral
    vtkFiltersSources
  TEST_DEPENDS
    vtkTestingCore
    vtkTestingRendering
    vtkRenderingOpenGL
  )
