vtk_module(vtkFiltersTracers
  DEPENDS
    vtkCommonExecutionModel
    vtkAMRCore
    vtkFiltersGeneral
    vtkFiltersSources
  TEST_DEPENDS
    vtkTestingCore
    vtkTestingRendering
    vtkRenderingOpenGL
  )
