vtk_module(vtkFiltersParallelMPI
  GROUPS
    MPI
  TEST_DEPENDS
    vtkIOXML
    vtkIOParallelXML
    vtkCommonDataModel
    vtkTestingCore
  KIT
    vtkParallel
  DEPENDS
    vtkCommonCore
    vtkCommonExecutionModel
    vtkCommonSystem
    vtkFiltersExtraction
    vtkImagingCore
  PRIVATE_DEPENDS
    vtkCommonDataModel
    vtkFiltersGeneral
    vtkFiltersParallel
    vtkIOLegacy
    vtkParallelCore
    vtkParallelMPI
  )
