vtk_module(vtkVolume2
  DEPENDS
    vtkCommonCore
    vtkCommonDataModel
    vtkCommonExecutionModel
    vtkFiltersSources
    vtkRenderingVolume
    vtkRenderingOpenGL
  TEST_DEPENDS
    vtkCommonCore
    vtkFiltersModeling
    vtkIOLegacy
    vtkIOXML
    vtkInteractionStyle
    vtkRenderingVolume
    vtkRenderingOpenGL
    vtkRenderingVolumeOpenGL
    vtkTestingCore
    vtkTestingRendering
)
