if(ANDROID OR APPLE_IOS) # No GL2PS on mobile
  return()
endif()
vtk_module(vtkRenderingGL2PSOpenGL2
  IMPLEMENTS
    vtkRenderingOpenGL2
  BACKEND
    OpenGL2
  TEST_DEPENDS
    vtkTestingRendering
    vtkInteractionStyle
  DEPENDS
    vtkRenderingOpenGL2
  PRIVATE_DEPENDS
    vtkCommonCore
    vtkCommonDataModel
    vtkCommonMath
    vtkRenderingCore
    vtkRenderingOpenGL2
    vtkgl2ps
)
