NAME
  VTK::RenderingGL2PSOpenGL2
LIBRARY_NAME
  vtkRenderingGL2PSOpenGL2
CONDITION
  NOT ANDROID AND NOT APPLE_IOS AND NOT VTK_OPENGL_USE_GLES
IMPLEMENTS
  VTK::RenderingOpenGL2
SPDX_LICENSE_IDENTIFIER
  BSD-3-Clause
SPDX_COPYRIGHT_TEXT
  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
DEPENDS
  VTK::RenderingOpenGL2
PRIVATE_DEPENDS
  VTK::CommonCore
  VTK::CommonDataModel
  VTK::CommonMath
  VTK::RenderingCore
  VTK::RenderingOpenGL2
  VTK::gl2ps
TEST_DEPENDS
  VTK::InteractionStyle
  VTK::TestingRendering
  VTK::gl2ps
