NAME
  VTK::FiltersReduction
LIBRARY_NAME
  vtkFiltersReduction
KIT
  VTK::Filters
GROUPS
  StandAlone
DESCRIPTION
  Tools to convert explicit (tabular) arrays into implicit (procedural) arrays, which can reduce memory consumption.
SPDX_LICENSE_IDENTIFIER
  BSD-3-Clause
SPDX_COPYRIGHT_TEXT
  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
DEPENDS
  VTK::CommonCore
  VTK::CommonExecutionModel
PRIVATE_DEPENDS
  VTK::CommonDataModel
TEST_DEPENDS
  VTK::CommonSystem
  VTK::FiltersSources
  VTK::TestingCore
