vtk_module(vtkFiltersParallelVerdict
  GROUPS
    MPI
  TEST_DEPENDS
    vtkParallelMPI
    vtkIOLegacy
    vtkTestingCore
  KIT
    vtkParallel
  DEPENDS
    vtkFiltersVerdict
    vtkParallelCore
  )
