vtk_module(vtkRenderingFreeTypeFontConfig
  IMPLEMENTS
    vtkRenderingFreeType
  TEST_DEPENDS
    vtkChartsCore
    vtkTestingRendering
    vtkViewsContext2D
    vtkRenderingContextOpenGL2
  EXCLUDE_FROM_WRAPPING
  KIT
    vtkRendering
  DEPENDS
    vtkRenderingFreeType
  PRIVATE_DEPENDS
    vtkCommonCore
    vtkRenderingCore
  )
