NAME
  VTK::IOXdmf2
LIBRARY_NAME
  vtkIOXdmf2
SPDX_LICENSE_IDENTIFIER
  BSD-3-Clause AND LicenseRef-BSD-4-Clause-Modif
SPDX_COPYRIGHT_TEXT
  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
  Copyright @ 2002 US Army Research Laboratory
SPDX_CUSTOM_LICENSE_FILE
  LICENSE
SPDX_CUSTOM_LICENSE_NAME
  BSD-4-Clause-Modif
LICENSE_FILES
  LICENSE
DEPENDS
  VTK::CommonCore
  VTK::CommonDataModel
  VTK::CommonExecutionModel
  VTK::IOLegacy
PRIVATE_DEPENDS
  VTK::IOXMLParser
  VTK::libxml2
  VTK::vtksys
  VTK::xdmf2
  VTK::FiltersExtraction
TEST_DEPENDS
  VTK::FiltersGeneral
  VTK::TestingCore
