# Linux/MPI Makefile for MapReduce examples, g++, MPI

CC =		gcc
CPP =		g++
CCFLAGS =	-g -O -I../src -DMPICH_IGNORE_CXX_SEEK
LINK =		g++
LINKFLAGS =	-g -O -L../src
USRLIB =	-lmrmpi -lmpich
SYSLIB =	-lpthread

LIB =		../src/libmrmpi.a

include Makefile.common
