vtk_module(vtkIOXML
  GROUPS
    StandAlone
  DEPENDS
    vtkIOXMLParser
    vtkIOGeometry
  PRIVATE_DEPENDS
    vtksys
  TEST_DEPENDS
    vtkFiltersAMR
    vtkFiltersCore
    vtkFiltersSources
    vtkImagingSources
    vtkInfovisCore
    vtkIOLegacy
    vtkRenderingOpenGL
    vtkTestingCore
    vtkTestingRendering
    vtkInteractionStyle
  )
