vtk_module(vtkFiltersParallel
  GROUPS
    MPI
  DEPENDS
    vtkParallelMPI
    vtkCosmo
    vtkFiltersGeneral
    vtkFiltersExtraction
    vtkFiltersModeling
    vtkFiltersSources
    vtkRenderingCore
  )
