vtk_module(vtkRenderingAnnotation
  GROUPS
    Rendering
  DEPENDS
    vtkRenderingFreeType
    vtkImagingColor
  TEST_DEPENDS
    vtkRenderingOpenGL
    vtkTestingRendering
    vtkInteractionStyle
    vtkRenderingLOD
  )
