vtk_module(vtkFiltersStatistics
  GROUPS
    StandAlone
  DEPENDS
    vtkCommonMath
    vtkCommonExecutionModel
    vtkCommonTransforms
    vtkCommonMisc
    vtkalglib
  TEST_DEPENDS
    vtkTestingCore
  )
