NAME
  VTK::DomainsMicroscopy
LIBRARY_NAME
  vtkDomainsMicroscopy
DESCRIPTION
  File readers for microscopy file formats
SPDX_LICENSE_IDENTIFIER
  BSD-3-Clause
SPDX_COPYRIGHT_TEXT
  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
DEPENDS
  VTK::IOImage
PRIVATE_DEPENDS
  VTK::CommonCore
  VTK::CommonDataModel
  VTK::CommonExecutionModel
TEST_DEPENDS
  VTK::InteractionImage
  VTK::RenderingContextOpenGL2
  VTK::TestingCore
  VTK::TestingRendering
