vtk_module(vtkRenderingVolumeOpenGL2
  IMPLEMENTS
    vtkRenderingVolume
  BACKEND
    OpenGL2
  IMPLEMENTATION_REQUIRED_BY_BACKEND
  TEST_DEPENDS
    vtkFiltersModeling
    vtkTestingCore
    vtkTestingRendering
    vtkImagingSources
    vtkImagingGeneral
    vtkInteractionStyle
    vtkInteractionWidgets
    vtkIOLegacy
  KIT
    vtkOpenGL
  DEPENDS
    vtkCommonCore
    vtkCommonDataModel
    vtkImagingCore
    vtkImagingMath
    vtkRenderingCore
    vtkRenderingOpenGL2
    vtkRenderingVolume
    vtkglew
  PRIVATE_DEPENDS
    vtkCommonMath
    vtkCommonSystem
    vtkCommonTransforms
    vtkFiltersCore
    vtkFiltersGeneral
    vtkFiltersSources
    vtksys
  )
