vtk_module(vtkRenderingVolumeOpenGL2
  TCL_NAME
    vtkRenderingVolumeOpenGLII
  DEPENDS
    vtkglew
    vtkRenderingOpenGL2
  IMPLEMENTS
    vtkRenderingVolume
  BACKEND
    OpenGL2
  IMPLEMENTATION_REQUIRED_BY_BACKEND
  PRIVATE_DEPENDS
    vtksys
    vtkFiltersGeneral
    vtkFiltersSources
  TEST_DEPENDS
    vtkTestingCore
    vtkTestingRendering
    vtkRenderingFreeType
    vtkImagingSources
    vtkImagingGeneral
    vtkInteractionStyle
  KIT
    vtkOpenGL
  )
