vtk_module(vtkDomainsChemistry
  GROUPS
    StandAlone
  TEST_DEPENDS
    vtkIOGeometry
    vtkIOLegacy
    vtkTestingCore
    vtkTestingRendering
    vtkInteractionStyle
    vtkRenderingOpenGL2
    vtkDomainsChemistryOpenGL2
  DEPENDS
    vtkCommonCore
    vtkCommonDataModel
    vtkCommonExecutionModel
    vtkIOLegacy
    vtkIOXMLParser
    vtkRenderingCore
  PRIVATE_DEPENDS
    vtkCommonTransforms
    vtkFiltersCore
    vtkFiltersGeneral
    vtkFiltersSources
    vtksys
  )
