NAME
  VTK::DomainsChemistry
LIBRARY_NAME
  vtkDomainsChemistry
DESCRIPTION
  Algorithms used in chemistry
IMPLEMENTABLE
GROUPS
  StandAlone
SPDX_LICENSE_IDENTIFIER
  BSD-3-Clause AND MIT
SPDX_COPYRIGHT_TEXT
  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
  Copyright (C) 2006-2008,2010 The Blue Obelisk Project (http://www.blueobelisk.org/)
DEPENDS
  VTK::CommonCore
  VTK::CommonDataModel
  VTK::CommonExecutionModel
  VTK::IOLegacy
  VTK::IOXMLParser
  VTK::RenderingCore
PRIVATE_DEPENDS
  VTK::CommonTransforms
  VTK::FiltersCore
  VTK::FiltersGeneral
  VTK::FiltersSources
  VTK::vtksys
TEST_DEPENDS
  VTK::CommonSystem
  VTK::DomainsChemistryOpenGL2
  VTK::FiltersGeometry
  VTK::InteractionStyle
  VTK::IOChemistry
  VTK::IOLegacy
  VTK::RenderingOpenGL2
  VTK::TestingCore
  VTK::TestingRendering
