vtk_module(vtkIOInfovis
  GROUPS
    StandAlone
  TEST_DEPENDS
    vtkInfovisLayout
    vtkRenderingCore
    vtkTestingRendering
  DEPENDS
    vtkCommonCore
    vtkCommonExecutionModel
    vtkIOLegacy
    vtkIOXML
  PRIVATE_DEPENDS
    vtkCommonDataModel
    vtkCommonMisc
    vtkIOCore
    vtkIOXMLParser
    vtkInfovisCore
    vtklibxml2
    vtksys
  )