vtk_module(vtkFiltersMatlab
  DEPENDS
    vtkCommonCore
    vtkCommonMath
    vtkCommonExecutionModel
    vtkCommonTransforms
    vtkCommonMisc
    vtkCommonDataModel
    vtksys
  EXCLUDE_FROM_WRAPPING
  EXCLUDE_FROM_WRAP_HIERARCHY
  EXCLUDE_FROM_ALL
  )
