vtk_module(vtkRenderingContextOpenGL2
  TCL_NAME
    vtkRenderingContextOpenGLTwo
  DEPENDS
    vtkRenderingOpenGL2
  IMPLEMENTS
    vtkRenderingContext2D
  BACKEND
    OpenGL2
  PRIVATE_DEPENDS
    vtkRenderingFreeType
  )
