#!/bin/env vtkpython
from vtk import *
xv = vtkDoubleArray()
yv = vtkDoubleArray()
xv.SetName( 'x' )
yv.SetName( 'y' )
tab = vtkTable()
xv.InsertNextValue( 0.0 )
xv.InsertNextValue( 1.0 )
xv.InsertNextValue( 0.0 )
xv.InsertNextValue( 1.0 )
xv.InsertNextValue( 5.0 )
yv.InsertNextValue( 0.0 )
yv.InsertNextValue( 0.0 )
yv.InsertNextValue( 1.0 )
yv.InsertNextValue( 1.0 )
yv.InsertNextValue( 12.0 )
tab.AddColumn( xv )
tab.AddColumn( yv )
km = vtkKMeansStatistics()
km.SetDefaultNumberOfClusters( 1 )
df = vtkKMeansDistanceFunctorCalculator()
km.SetDistanceFunctor( df )
df.SetDistanceExpression( 'sqrt( (x0-y0)*(x0-y0) + (x1-y1)*(x1-y1) )' )
km.SetInput( tab )
km.SetColumnStatus( 'x', 1 )
km.SetColumnStatus( 'y', 1 )
km.RequestSelectedColumns()
km.SetLearnOption( 1 )
km.SetDeriveOption( 1 )
km.SetAssessOption( 1 )
km.Update()
t2 = km.GetOutput( 0 )
t2.Dump(10)

