// SPDX-FileCopyrightText: Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
// SPDX-License-Identifier: BSD-3-Clause
// Generated by Rendering/WebGPU/generate_proc_dispatch.py. Do not edit.

#include "Private/vtkWebGPUProcDispatch.h"

#if !defined(__EMSCRIPTEN__)

VTK_ABI_NAMESPACE_BEGIN
vtkWebGPUProcDispatch vtkWebGPUProcs;

const char* vtkWebGPUProcDispatchResolve(WGPUProc (*getProcAddress)(WGPUStringView))
{
  if (getProcAddress == nullptr)
  {
    return "wgpuGetProcAddress";
  }
  vtkWebGPUProcDispatch resolved;
  resolved.CreateInstance = reinterpret_cast<WGPUProcCreateInstance>(
    getProcAddress(WGPUStringView{ "wgpuCreateInstance", WGPU_STRLEN }));
  if (resolved.CreateInstance == nullptr)
  {
    return "wgpuCreateInstance";
  }
  resolved.GetInstanceFeatures = reinterpret_cast<WGPUProcGetInstanceFeatures>(
    getProcAddress(WGPUStringView{ "wgpuGetInstanceFeatures", WGPU_STRLEN }));
  if (resolved.GetInstanceFeatures == nullptr)
  {
    return "wgpuGetInstanceFeatures";
  }
  resolved.GetInstanceLimits = reinterpret_cast<WGPUProcGetInstanceLimits>(
    getProcAddress(WGPUStringView{ "wgpuGetInstanceLimits", WGPU_STRLEN }));
  if (resolved.GetInstanceLimits == nullptr)
  {
    return "wgpuGetInstanceLimits";
  }
  resolved.HasInstanceFeature = reinterpret_cast<WGPUProcHasInstanceFeature>(
    getProcAddress(WGPUStringView{ "wgpuHasInstanceFeature", WGPU_STRLEN }));
  if (resolved.HasInstanceFeature == nullptr)
  {
    return "wgpuHasInstanceFeature";
  }
  resolved.GetProcAddress = reinterpret_cast<WGPUProcGetProcAddress>(
    getProcAddress(WGPUStringView{ "wgpuGetProcAddress", WGPU_STRLEN }));
  if (resolved.GetProcAddress == nullptr)
  {
    return "wgpuGetProcAddress";
  }
  resolved.AdapterGetFeatures = reinterpret_cast<WGPUProcAdapterGetFeatures>(
    getProcAddress(WGPUStringView{ "wgpuAdapterGetFeatures", WGPU_STRLEN }));
  if (resolved.AdapterGetFeatures == nullptr)
  {
    return "wgpuAdapterGetFeatures";
  }
  resolved.AdapterGetInfo = reinterpret_cast<WGPUProcAdapterGetInfo>(
    getProcAddress(WGPUStringView{ "wgpuAdapterGetInfo", WGPU_STRLEN }));
  if (resolved.AdapterGetInfo == nullptr)
  {
    return "wgpuAdapterGetInfo";
  }
  resolved.AdapterGetLimits = reinterpret_cast<WGPUProcAdapterGetLimits>(
    getProcAddress(WGPUStringView{ "wgpuAdapterGetLimits", WGPU_STRLEN }));
  if (resolved.AdapterGetLimits == nullptr)
  {
    return "wgpuAdapterGetLimits";
  }
  resolved.AdapterHasFeature = reinterpret_cast<WGPUProcAdapterHasFeature>(
    getProcAddress(WGPUStringView{ "wgpuAdapterHasFeature", WGPU_STRLEN }));
  if (resolved.AdapterHasFeature == nullptr)
  {
    return "wgpuAdapterHasFeature";
  }
  resolved.AdapterRequestDevice = reinterpret_cast<WGPUProcAdapterRequestDevice>(
    getProcAddress(WGPUStringView{ "wgpuAdapterRequestDevice", WGPU_STRLEN }));
  if (resolved.AdapterRequestDevice == nullptr)
  {
    return "wgpuAdapterRequestDevice";
  }
  resolved.AdapterAddRef = reinterpret_cast<WGPUProcAdapterAddRef>(
    getProcAddress(WGPUStringView{ "wgpuAdapterAddRef", WGPU_STRLEN }));
  if (resolved.AdapterAddRef == nullptr)
  {
    return "wgpuAdapterAddRef";
  }
  resolved.AdapterRelease = reinterpret_cast<WGPUProcAdapterRelease>(
    getProcAddress(WGPUStringView{ "wgpuAdapterRelease", WGPU_STRLEN }));
  if (resolved.AdapterRelease == nullptr)
  {
    return "wgpuAdapterRelease";
  }
  resolved.AdapterInfoFreeMembers = reinterpret_cast<WGPUProcAdapterInfoFreeMembers>(
    getProcAddress(WGPUStringView{ "wgpuAdapterInfoFreeMembers", WGPU_STRLEN }));
  if (resolved.AdapterInfoFreeMembers == nullptr)
  {
    return "wgpuAdapterInfoFreeMembers";
  }
  resolved.BindGroupSetLabel = reinterpret_cast<WGPUProcBindGroupSetLabel>(
    getProcAddress(WGPUStringView{ "wgpuBindGroupSetLabel", WGPU_STRLEN }));
  if (resolved.BindGroupSetLabel == nullptr)
  {
    return "wgpuBindGroupSetLabel";
  }
  resolved.BindGroupAddRef = reinterpret_cast<WGPUProcBindGroupAddRef>(
    getProcAddress(WGPUStringView{ "wgpuBindGroupAddRef", WGPU_STRLEN }));
  if (resolved.BindGroupAddRef == nullptr)
  {
    return "wgpuBindGroupAddRef";
  }
  resolved.BindGroupRelease = reinterpret_cast<WGPUProcBindGroupRelease>(
    getProcAddress(WGPUStringView{ "wgpuBindGroupRelease", WGPU_STRLEN }));
  if (resolved.BindGroupRelease == nullptr)
  {
    return "wgpuBindGroupRelease";
  }
  resolved.BindGroupLayoutSetLabel = reinterpret_cast<WGPUProcBindGroupLayoutSetLabel>(
    getProcAddress(WGPUStringView{ "wgpuBindGroupLayoutSetLabel", WGPU_STRLEN }));
  if (resolved.BindGroupLayoutSetLabel == nullptr)
  {
    return "wgpuBindGroupLayoutSetLabel";
  }
  resolved.BindGroupLayoutAddRef = reinterpret_cast<WGPUProcBindGroupLayoutAddRef>(
    getProcAddress(WGPUStringView{ "wgpuBindGroupLayoutAddRef", WGPU_STRLEN }));
  if (resolved.BindGroupLayoutAddRef == nullptr)
  {
    return "wgpuBindGroupLayoutAddRef";
  }
  resolved.BindGroupLayoutRelease = reinterpret_cast<WGPUProcBindGroupLayoutRelease>(
    getProcAddress(WGPUStringView{ "wgpuBindGroupLayoutRelease", WGPU_STRLEN }));
  if (resolved.BindGroupLayoutRelease == nullptr)
  {
    return "wgpuBindGroupLayoutRelease";
  }
  resolved.BufferDestroy = reinterpret_cast<WGPUProcBufferDestroy>(
    getProcAddress(WGPUStringView{ "wgpuBufferDestroy", WGPU_STRLEN }));
  if (resolved.BufferDestroy == nullptr)
  {
    return "wgpuBufferDestroy";
  }
  resolved.BufferGetConstMappedRange = reinterpret_cast<WGPUProcBufferGetConstMappedRange>(
    getProcAddress(WGPUStringView{ "wgpuBufferGetConstMappedRange", WGPU_STRLEN }));
  if (resolved.BufferGetConstMappedRange == nullptr)
  {
    return "wgpuBufferGetConstMappedRange";
  }
  resolved.BufferGetMappedRange = reinterpret_cast<WGPUProcBufferGetMappedRange>(
    getProcAddress(WGPUStringView{ "wgpuBufferGetMappedRange", WGPU_STRLEN }));
  if (resolved.BufferGetMappedRange == nullptr)
  {
    return "wgpuBufferGetMappedRange";
  }
  resolved.BufferGetMapState = reinterpret_cast<WGPUProcBufferGetMapState>(
    getProcAddress(WGPUStringView{ "wgpuBufferGetMapState", WGPU_STRLEN }));
  if (resolved.BufferGetMapState == nullptr)
  {
    return "wgpuBufferGetMapState";
  }
  resolved.BufferGetSize = reinterpret_cast<WGPUProcBufferGetSize>(
    getProcAddress(WGPUStringView{ "wgpuBufferGetSize", WGPU_STRLEN }));
  if (resolved.BufferGetSize == nullptr)
  {
    return "wgpuBufferGetSize";
  }
  resolved.BufferGetUsage = reinterpret_cast<WGPUProcBufferGetUsage>(
    getProcAddress(WGPUStringView{ "wgpuBufferGetUsage", WGPU_STRLEN }));
  if (resolved.BufferGetUsage == nullptr)
  {
    return "wgpuBufferGetUsage";
  }
  resolved.BufferMapAsync = reinterpret_cast<WGPUProcBufferMapAsync>(
    getProcAddress(WGPUStringView{ "wgpuBufferMapAsync", WGPU_STRLEN }));
  if (resolved.BufferMapAsync == nullptr)
  {
    return "wgpuBufferMapAsync";
  }
  resolved.BufferReadMappedRange = reinterpret_cast<WGPUProcBufferReadMappedRange>(
    getProcAddress(WGPUStringView{ "wgpuBufferReadMappedRange", WGPU_STRLEN }));
  if (resolved.BufferReadMappedRange == nullptr)
  {
    return "wgpuBufferReadMappedRange";
  }
  resolved.BufferSetLabel = reinterpret_cast<WGPUProcBufferSetLabel>(
    getProcAddress(WGPUStringView{ "wgpuBufferSetLabel", WGPU_STRLEN }));
  if (resolved.BufferSetLabel == nullptr)
  {
    return "wgpuBufferSetLabel";
  }
  resolved.BufferUnmap = reinterpret_cast<WGPUProcBufferUnmap>(
    getProcAddress(WGPUStringView{ "wgpuBufferUnmap", WGPU_STRLEN }));
  if (resolved.BufferUnmap == nullptr)
  {
    return "wgpuBufferUnmap";
  }
  resolved.BufferWriteMappedRange = reinterpret_cast<WGPUProcBufferWriteMappedRange>(
    getProcAddress(WGPUStringView{ "wgpuBufferWriteMappedRange", WGPU_STRLEN }));
  if (resolved.BufferWriteMappedRange == nullptr)
  {
    return "wgpuBufferWriteMappedRange";
  }
  resolved.BufferAddRef = reinterpret_cast<WGPUProcBufferAddRef>(
    getProcAddress(WGPUStringView{ "wgpuBufferAddRef", WGPU_STRLEN }));
  if (resolved.BufferAddRef == nullptr)
  {
    return "wgpuBufferAddRef";
  }
  resolved.BufferRelease = reinterpret_cast<WGPUProcBufferRelease>(
    getProcAddress(WGPUStringView{ "wgpuBufferRelease", WGPU_STRLEN }));
  if (resolved.BufferRelease == nullptr)
  {
    return "wgpuBufferRelease";
  }
  resolved.CommandBufferSetLabel = reinterpret_cast<WGPUProcCommandBufferSetLabel>(
    getProcAddress(WGPUStringView{ "wgpuCommandBufferSetLabel", WGPU_STRLEN }));
  if (resolved.CommandBufferSetLabel == nullptr)
  {
    return "wgpuCommandBufferSetLabel";
  }
  resolved.CommandBufferAddRef = reinterpret_cast<WGPUProcCommandBufferAddRef>(
    getProcAddress(WGPUStringView{ "wgpuCommandBufferAddRef", WGPU_STRLEN }));
  if (resolved.CommandBufferAddRef == nullptr)
  {
    return "wgpuCommandBufferAddRef";
  }
  resolved.CommandBufferRelease = reinterpret_cast<WGPUProcCommandBufferRelease>(
    getProcAddress(WGPUStringView{ "wgpuCommandBufferRelease", WGPU_STRLEN }));
  if (resolved.CommandBufferRelease == nullptr)
  {
    return "wgpuCommandBufferRelease";
  }
  resolved.CommandEncoderBeginComputePass =
    reinterpret_cast<WGPUProcCommandEncoderBeginComputePass>(
      getProcAddress(WGPUStringView{ "wgpuCommandEncoderBeginComputePass", WGPU_STRLEN }));
  if (resolved.CommandEncoderBeginComputePass == nullptr)
  {
    return "wgpuCommandEncoderBeginComputePass";
  }
  resolved.CommandEncoderBeginRenderPass = reinterpret_cast<WGPUProcCommandEncoderBeginRenderPass>(
    getProcAddress(WGPUStringView{ "wgpuCommandEncoderBeginRenderPass", WGPU_STRLEN }));
  if (resolved.CommandEncoderBeginRenderPass == nullptr)
  {
    return "wgpuCommandEncoderBeginRenderPass";
  }
  resolved.CommandEncoderClearBuffer = reinterpret_cast<WGPUProcCommandEncoderClearBuffer>(
    getProcAddress(WGPUStringView{ "wgpuCommandEncoderClearBuffer", WGPU_STRLEN }));
  if (resolved.CommandEncoderClearBuffer == nullptr)
  {
    return "wgpuCommandEncoderClearBuffer";
  }
  resolved.CommandEncoderCopyBufferToBuffer =
    reinterpret_cast<WGPUProcCommandEncoderCopyBufferToBuffer>(
      getProcAddress(WGPUStringView{ "wgpuCommandEncoderCopyBufferToBuffer", WGPU_STRLEN }));
  if (resolved.CommandEncoderCopyBufferToBuffer == nullptr)
  {
    return "wgpuCommandEncoderCopyBufferToBuffer";
  }
  resolved.CommandEncoderCopyBufferToTexture =
    reinterpret_cast<WGPUProcCommandEncoderCopyBufferToTexture>(
      getProcAddress(WGPUStringView{ "wgpuCommandEncoderCopyBufferToTexture", WGPU_STRLEN }));
  if (resolved.CommandEncoderCopyBufferToTexture == nullptr)
  {
    return "wgpuCommandEncoderCopyBufferToTexture";
  }
  resolved.CommandEncoderCopyTextureToBuffer =
    reinterpret_cast<WGPUProcCommandEncoderCopyTextureToBuffer>(
      getProcAddress(WGPUStringView{ "wgpuCommandEncoderCopyTextureToBuffer", WGPU_STRLEN }));
  if (resolved.CommandEncoderCopyTextureToBuffer == nullptr)
  {
    return "wgpuCommandEncoderCopyTextureToBuffer";
  }
  resolved.CommandEncoderCopyTextureToTexture =
    reinterpret_cast<WGPUProcCommandEncoderCopyTextureToTexture>(
      getProcAddress(WGPUStringView{ "wgpuCommandEncoderCopyTextureToTexture", WGPU_STRLEN }));
  if (resolved.CommandEncoderCopyTextureToTexture == nullptr)
  {
    return "wgpuCommandEncoderCopyTextureToTexture";
  }
  resolved.CommandEncoderFinish = reinterpret_cast<WGPUProcCommandEncoderFinish>(
    getProcAddress(WGPUStringView{ "wgpuCommandEncoderFinish", WGPU_STRLEN }));
  if (resolved.CommandEncoderFinish == nullptr)
  {
    return "wgpuCommandEncoderFinish";
  }
  resolved.CommandEncoderInsertDebugMarker =
    reinterpret_cast<WGPUProcCommandEncoderInsertDebugMarker>(
      getProcAddress(WGPUStringView{ "wgpuCommandEncoderInsertDebugMarker", WGPU_STRLEN }));
  if (resolved.CommandEncoderInsertDebugMarker == nullptr)
  {
    return "wgpuCommandEncoderInsertDebugMarker";
  }
  resolved.CommandEncoderPopDebugGroup = reinterpret_cast<WGPUProcCommandEncoderPopDebugGroup>(
    getProcAddress(WGPUStringView{ "wgpuCommandEncoderPopDebugGroup", WGPU_STRLEN }));
  if (resolved.CommandEncoderPopDebugGroup == nullptr)
  {
    return "wgpuCommandEncoderPopDebugGroup";
  }
  resolved.CommandEncoderPushDebugGroup = reinterpret_cast<WGPUProcCommandEncoderPushDebugGroup>(
    getProcAddress(WGPUStringView{ "wgpuCommandEncoderPushDebugGroup", WGPU_STRLEN }));
  if (resolved.CommandEncoderPushDebugGroup == nullptr)
  {
    return "wgpuCommandEncoderPushDebugGroup";
  }
  resolved.CommandEncoderResolveQuerySet = reinterpret_cast<WGPUProcCommandEncoderResolveQuerySet>(
    getProcAddress(WGPUStringView{ "wgpuCommandEncoderResolveQuerySet", WGPU_STRLEN }));
  if (resolved.CommandEncoderResolveQuerySet == nullptr)
  {
    return "wgpuCommandEncoderResolveQuerySet";
  }
  resolved.CommandEncoderSetLabel = reinterpret_cast<WGPUProcCommandEncoderSetLabel>(
    getProcAddress(WGPUStringView{ "wgpuCommandEncoderSetLabel", WGPU_STRLEN }));
  if (resolved.CommandEncoderSetLabel == nullptr)
  {
    return "wgpuCommandEncoderSetLabel";
  }
  resolved.CommandEncoderWriteTimestamp = reinterpret_cast<WGPUProcCommandEncoderWriteTimestamp>(
    getProcAddress(WGPUStringView{ "wgpuCommandEncoderWriteTimestamp", WGPU_STRLEN }));
  if (resolved.CommandEncoderWriteTimestamp == nullptr)
  {
    return "wgpuCommandEncoderWriteTimestamp";
  }
  resolved.CommandEncoderAddRef = reinterpret_cast<WGPUProcCommandEncoderAddRef>(
    getProcAddress(WGPUStringView{ "wgpuCommandEncoderAddRef", WGPU_STRLEN }));
  if (resolved.CommandEncoderAddRef == nullptr)
  {
    return "wgpuCommandEncoderAddRef";
  }
  resolved.CommandEncoderRelease = reinterpret_cast<WGPUProcCommandEncoderRelease>(
    getProcAddress(WGPUStringView{ "wgpuCommandEncoderRelease", WGPU_STRLEN }));
  if (resolved.CommandEncoderRelease == nullptr)
  {
    return "wgpuCommandEncoderRelease";
  }
  resolved.ComputePassEncoderDispatchWorkgroups =
    reinterpret_cast<WGPUProcComputePassEncoderDispatchWorkgroups>(
      getProcAddress(WGPUStringView{ "wgpuComputePassEncoderDispatchWorkgroups", WGPU_STRLEN }));
  if (resolved.ComputePassEncoderDispatchWorkgroups == nullptr)
  {
    return "wgpuComputePassEncoderDispatchWorkgroups";
  }
  resolved.ComputePassEncoderDispatchWorkgroupsIndirect =
    reinterpret_cast<WGPUProcComputePassEncoderDispatchWorkgroupsIndirect>(getProcAddress(
      WGPUStringView{ "wgpuComputePassEncoderDispatchWorkgroupsIndirect", WGPU_STRLEN }));
  if (resolved.ComputePassEncoderDispatchWorkgroupsIndirect == nullptr)
  {
    return "wgpuComputePassEncoderDispatchWorkgroupsIndirect";
  }
  resolved.ComputePassEncoderEnd = reinterpret_cast<WGPUProcComputePassEncoderEnd>(
    getProcAddress(WGPUStringView{ "wgpuComputePassEncoderEnd", WGPU_STRLEN }));
  if (resolved.ComputePassEncoderEnd == nullptr)
  {
    return "wgpuComputePassEncoderEnd";
  }
  resolved.ComputePassEncoderInsertDebugMarker =
    reinterpret_cast<WGPUProcComputePassEncoderInsertDebugMarker>(
      getProcAddress(WGPUStringView{ "wgpuComputePassEncoderInsertDebugMarker", WGPU_STRLEN }));
  if (resolved.ComputePassEncoderInsertDebugMarker == nullptr)
  {
    return "wgpuComputePassEncoderInsertDebugMarker";
  }
  resolved.ComputePassEncoderPopDebugGroup =
    reinterpret_cast<WGPUProcComputePassEncoderPopDebugGroup>(
      getProcAddress(WGPUStringView{ "wgpuComputePassEncoderPopDebugGroup", WGPU_STRLEN }));
  if (resolved.ComputePassEncoderPopDebugGroup == nullptr)
  {
    return "wgpuComputePassEncoderPopDebugGroup";
  }
  resolved.ComputePassEncoderPushDebugGroup =
    reinterpret_cast<WGPUProcComputePassEncoderPushDebugGroup>(
      getProcAddress(WGPUStringView{ "wgpuComputePassEncoderPushDebugGroup", WGPU_STRLEN }));
  if (resolved.ComputePassEncoderPushDebugGroup == nullptr)
  {
    return "wgpuComputePassEncoderPushDebugGroup";
  }
  resolved.ComputePassEncoderSetBindGroup =
    reinterpret_cast<WGPUProcComputePassEncoderSetBindGroup>(
      getProcAddress(WGPUStringView{ "wgpuComputePassEncoderSetBindGroup", WGPU_STRLEN }));
  if (resolved.ComputePassEncoderSetBindGroup == nullptr)
  {
    return "wgpuComputePassEncoderSetBindGroup";
  }
  resolved.ComputePassEncoderSetImmediates =
    reinterpret_cast<WGPUProcComputePassEncoderSetImmediates>(
      getProcAddress(WGPUStringView{ "wgpuComputePassEncoderSetImmediates", WGPU_STRLEN }));
  if (resolved.ComputePassEncoderSetImmediates == nullptr)
  {
    return "wgpuComputePassEncoderSetImmediates";
  }
  resolved.ComputePassEncoderSetLabel = reinterpret_cast<WGPUProcComputePassEncoderSetLabel>(
    getProcAddress(WGPUStringView{ "wgpuComputePassEncoderSetLabel", WGPU_STRLEN }));
  if (resolved.ComputePassEncoderSetLabel == nullptr)
  {
    return "wgpuComputePassEncoderSetLabel";
  }
  resolved.ComputePassEncoderSetPipeline = reinterpret_cast<WGPUProcComputePassEncoderSetPipeline>(
    getProcAddress(WGPUStringView{ "wgpuComputePassEncoderSetPipeline", WGPU_STRLEN }));
  if (resolved.ComputePassEncoderSetPipeline == nullptr)
  {
    return "wgpuComputePassEncoderSetPipeline";
  }
  resolved.ComputePassEncoderAddRef = reinterpret_cast<WGPUProcComputePassEncoderAddRef>(
    getProcAddress(WGPUStringView{ "wgpuComputePassEncoderAddRef", WGPU_STRLEN }));
  if (resolved.ComputePassEncoderAddRef == nullptr)
  {
    return "wgpuComputePassEncoderAddRef";
  }
  resolved.ComputePassEncoderRelease = reinterpret_cast<WGPUProcComputePassEncoderRelease>(
    getProcAddress(WGPUStringView{ "wgpuComputePassEncoderRelease", WGPU_STRLEN }));
  if (resolved.ComputePassEncoderRelease == nullptr)
  {
    return "wgpuComputePassEncoderRelease";
  }
  resolved.ComputePipelineGetBindGroupLayout =
    reinterpret_cast<WGPUProcComputePipelineGetBindGroupLayout>(
      getProcAddress(WGPUStringView{ "wgpuComputePipelineGetBindGroupLayout", WGPU_STRLEN }));
  if (resolved.ComputePipelineGetBindGroupLayout == nullptr)
  {
    return "wgpuComputePipelineGetBindGroupLayout";
  }
  resolved.ComputePipelineSetLabel = reinterpret_cast<WGPUProcComputePipelineSetLabel>(
    getProcAddress(WGPUStringView{ "wgpuComputePipelineSetLabel", WGPU_STRLEN }));
  if (resolved.ComputePipelineSetLabel == nullptr)
  {
    return "wgpuComputePipelineSetLabel";
  }
  resolved.ComputePipelineAddRef = reinterpret_cast<WGPUProcComputePipelineAddRef>(
    getProcAddress(WGPUStringView{ "wgpuComputePipelineAddRef", WGPU_STRLEN }));
  if (resolved.ComputePipelineAddRef == nullptr)
  {
    return "wgpuComputePipelineAddRef";
  }
  resolved.ComputePipelineRelease = reinterpret_cast<WGPUProcComputePipelineRelease>(
    getProcAddress(WGPUStringView{ "wgpuComputePipelineRelease", WGPU_STRLEN }));
  if (resolved.ComputePipelineRelease == nullptr)
  {
    return "wgpuComputePipelineRelease";
  }
  resolved.DeviceCreateBindGroup = reinterpret_cast<WGPUProcDeviceCreateBindGroup>(
    getProcAddress(WGPUStringView{ "wgpuDeviceCreateBindGroup", WGPU_STRLEN }));
  if (resolved.DeviceCreateBindGroup == nullptr)
  {
    return "wgpuDeviceCreateBindGroup";
  }
  resolved.DeviceCreateBindGroupLayout = reinterpret_cast<WGPUProcDeviceCreateBindGroupLayout>(
    getProcAddress(WGPUStringView{ "wgpuDeviceCreateBindGroupLayout", WGPU_STRLEN }));
  if (resolved.DeviceCreateBindGroupLayout == nullptr)
  {
    return "wgpuDeviceCreateBindGroupLayout";
  }
  resolved.DeviceCreateBuffer = reinterpret_cast<WGPUProcDeviceCreateBuffer>(
    getProcAddress(WGPUStringView{ "wgpuDeviceCreateBuffer", WGPU_STRLEN }));
  if (resolved.DeviceCreateBuffer == nullptr)
  {
    return "wgpuDeviceCreateBuffer";
  }
  resolved.DeviceCreateCommandEncoder = reinterpret_cast<WGPUProcDeviceCreateCommandEncoder>(
    getProcAddress(WGPUStringView{ "wgpuDeviceCreateCommandEncoder", WGPU_STRLEN }));
  if (resolved.DeviceCreateCommandEncoder == nullptr)
  {
    return "wgpuDeviceCreateCommandEncoder";
  }
  resolved.DeviceCreateComputePipeline = reinterpret_cast<WGPUProcDeviceCreateComputePipeline>(
    getProcAddress(WGPUStringView{ "wgpuDeviceCreateComputePipeline", WGPU_STRLEN }));
  if (resolved.DeviceCreateComputePipeline == nullptr)
  {
    return "wgpuDeviceCreateComputePipeline";
  }
  resolved.DeviceCreateComputePipelineAsync =
    reinterpret_cast<WGPUProcDeviceCreateComputePipelineAsync>(
      getProcAddress(WGPUStringView{ "wgpuDeviceCreateComputePipelineAsync", WGPU_STRLEN }));
  if (resolved.DeviceCreateComputePipelineAsync == nullptr)
  {
    return "wgpuDeviceCreateComputePipelineAsync";
  }
  resolved.DeviceCreatePipelineLayout = reinterpret_cast<WGPUProcDeviceCreatePipelineLayout>(
    getProcAddress(WGPUStringView{ "wgpuDeviceCreatePipelineLayout", WGPU_STRLEN }));
  if (resolved.DeviceCreatePipelineLayout == nullptr)
  {
    return "wgpuDeviceCreatePipelineLayout";
  }
  resolved.DeviceCreateQuerySet = reinterpret_cast<WGPUProcDeviceCreateQuerySet>(
    getProcAddress(WGPUStringView{ "wgpuDeviceCreateQuerySet", WGPU_STRLEN }));
  if (resolved.DeviceCreateQuerySet == nullptr)
  {
    return "wgpuDeviceCreateQuerySet";
  }
  resolved.DeviceCreateRenderBundleEncoder =
    reinterpret_cast<WGPUProcDeviceCreateRenderBundleEncoder>(
      getProcAddress(WGPUStringView{ "wgpuDeviceCreateRenderBundleEncoder", WGPU_STRLEN }));
  if (resolved.DeviceCreateRenderBundleEncoder == nullptr)
  {
    return "wgpuDeviceCreateRenderBundleEncoder";
  }
  resolved.DeviceCreateRenderPipeline = reinterpret_cast<WGPUProcDeviceCreateRenderPipeline>(
    getProcAddress(WGPUStringView{ "wgpuDeviceCreateRenderPipeline", WGPU_STRLEN }));
  if (resolved.DeviceCreateRenderPipeline == nullptr)
  {
    return "wgpuDeviceCreateRenderPipeline";
  }
  resolved.DeviceCreateRenderPipelineAsync =
    reinterpret_cast<WGPUProcDeviceCreateRenderPipelineAsync>(
      getProcAddress(WGPUStringView{ "wgpuDeviceCreateRenderPipelineAsync", WGPU_STRLEN }));
  if (resolved.DeviceCreateRenderPipelineAsync == nullptr)
  {
    return "wgpuDeviceCreateRenderPipelineAsync";
  }
  resolved.DeviceCreateSampler = reinterpret_cast<WGPUProcDeviceCreateSampler>(
    getProcAddress(WGPUStringView{ "wgpuDeviceCreateSampler", WGPU_STRLEN }));
  if (resolved.DeviceCreateSampler == nullptr)
  {
    return "wgpuDeviceCreateSampler";
  }
  resolved.DeviceCreateShaderModule = reinterpret_cast<WGPUProcDeviceCreateShaderModule>(
    getProcAddress(WGPUStringView{ "wgpuDeviceCreateShaderModule", WGPU_STRLEN }));
  if (resolved.DeviceCreateShaderModule == nullptr)
  {
    return "wgpuDeviceCreateShaderModule";
  }
  resolved.DeviceCreateTexture = reinterpret_cast<WGPUProcDeviceCreateTexture>(
    getProcAddress(WGPUStringView{ "wgpuDeviceCreateTexture", WGPU_STRLEN }));
  if (resolved.DeviceCreateTexture == nullptr)
  {
    return "wgpuDeviceCreateTexture";
  }
  resolved.DeviceDestroy = reinterpret_cast<WGPUProcDeviceDestroy>(
    getProcAddress(WGPUStringView{ "wgpuDeviceDestroy", WGPU_STRLEN }));
  if (resolved.DeviceDestroy == nullptr)
  {
    return "wgpuDeviceDestroy";
  }
  resolved.DeviceGetAdapterInfo = reinterpret_cast<WGPUProcDeviceGetAdapterInfo>(
    getProcAddress(WGPUStringView{ "wgpuDeviceGetAdapterInfo", WGPU_STRLEN }));
  if (resolved.DeviceGetAdapterInfo == nullptr)
  {
    return "wgpuDeviceGetAdapterInfo";
  }
  resolved.DeviceGetFeatures = reinterpret_cast<WGPUProcDeviceGetFeatures>(
    getProcAddress(WGPUStringView{ "wgpuDeviceGetFeatures", WGPU_STRLEN }));
  if (resolved.DeviceGetFeatures == nullptr)
  {
    return "wgpuDeviceGetFeatures";
  }
  resolved.DeviceGetLimits = reinterpret_cast<WGPUProcDeviceGetLimits>(
    getProcAddress(WGPUStringView{ "wgpuDeviceGetLimits", WGPU_STRLEN }));
  if (resolved.DeviceGetLimits == nullptr)
  {
    return "wgpuDeviceGetLimits";
  }
  resolved.DeviceGetLostFuture = reinterpret_cast<WGPUProcDeviceGetLostFuture>(
    getProcAddress(WGPUStringView{ "wgpuDeviceGetLostFuture", WGPU_STRLEN }));
  if (resolved.DeviceGetLostFuture == nullptr)
  {
    return "wgpuDeviceGetLostFuture";
  }
  resolved.DeviceGetQueue = reinterpret_cast<WGPUProcDeviceGetQueue>(
    getProcAddress(WGPUStringView{ "wgpuDeviceGetQueue", WGPU_STRLEN }));
  if (resolved.DeviceGetQueue == nullptr)
  {
    return "wgpuDeviceGetQueue";
  }
  resolved.DeviceHasFeature = reinterpret_cast<WGPUProcDeviceHasFeature>(
    getProcAddress(WGPUStringView{ "wgpuDeviceHasFeature", WGPU_STRLEN }));
  if (resolved.DeviceHasFeature == nullptr)
  {
    return "wgpuDeviceHasFeature";
  }
  resolved.DevicePopErrorScope = reinterpret_cast<WGPUProcDevicePopErrorScope>(
    getProcAddress(WGPUStringView{ "wgpuDevicePopErrorScope", WGPU_STRLEN }));
  if (resolved.DevicePopErrorScope == nullptr)
  {
    return "wgpuDevicePopErrorScope";
  }
  resolved.DevicePushErrorScope = reinterpret_cast<WGPUProcDevicePushErrorScope>(
    getProcAddress(WGPUStringView{ "wgpuDevicePushErrorScope", WGPU_STRLEN }));
  if (resolved.DevicePushErrorScope == nullptr)
  {
    return "wgpuDevicePushErrorScope";
  }
  resolved.DeviceSetLabel = reinterpret_cast<WGPUProcDeviceSetLabel>(
    getProcAddress(WGPUStringView{ "wgpuDeviceSetLabel", WGPU_STRLEN }));
  if (resolved.DeviceSetLabel == nullptr)
  {
    return "wgpuDeviceSetLabel";
  }
  resolved.DeviceAddRef = reinterpret_cast<WGPUProcDeviceAddRef>(
    getProcAddress(WGPUStringView{ "wgpuDeviceAddRef", WGPU_STRLEN }));
  if (resolved.DeviceAddRef == nullptr)
  {
    return "wgpuDeviceAddRef";
  }
  resolved.DeviceRelease = reinterpret_cast<WGPUProcDeviceRelease>(
    getProcAddress(WGPUStringView{ "wgpuDeviceRelease", WGPU_STRLEN }));
  if (resolved.DeviceRelease == nullptr)
  {
    return "wgpuDeviceRelease";
  }
  resolved.ExternalTextureSetLabel = reinterpret_cast<WGPUProcExternalTextureSetLabel>(
    getProcAddress(WGPUStringView{ "wgpuExternalTextureSetLabel", WGPU_STRLEN }));
  if (resolved.ExternalTextureSetLabel == nullptr)
  {
    return "wgpuExternalTextureSetLabel";
  }
  resolved.ExternalTextureAddRef = reinterpret_cast<WGPUProcExternalTextureAddRef>(
    getProcAddress(WGPUStringView{ "wgpuExternalTextureAddRef", WGPU_STRLEN }));
  if (resolved.ExternalTextureAddRef == nullptr)
  {
    return "wgpuExternalTextureAddRef";
  }
  resolved.ExternalTextureRelease = reinterpret_cast<WGPUProcExternalTextureRelease>(
    getProcAddress(WGPUStringView{ "wgpuExternalTextureRelease", WGPU_STRLEN }));
  if (resolved.ExternalTextureRelease == nullptr)
  {
    return "wgpuExternalTextureRelease";
  }
  resolved.InstanceCreateSurface = reinterpret_cast<WGPUProcInstanceCreateSurface>(
    getProcAddress(WGPUStringView{ "wgpuInstanceCreateSurface", WGPU_STRLEN }));
  if (resolved.InstanceCreateSurface == nullptr)
  {
    return "wgpuInstanceCreateSurface";
  }
  resolved.InstanceGetWGSLLanguageFeatures =
    reinterpret_cast<WGPUProcInstanceGetWGSLLanguageFeatures>(
      getProcAddress(WGPUStringView{ "wgpuInstanceGetWGSLLanguageFeatures", WGPU_STRLEN }));
  if (resolved.InstanceGetWGSLLanguageFeatures == nullptr)
  {
    return "wgpuInstanceGetWGSLLanguageFeatures";
  }
  resolved.InstanceHasWGSLLanguageFeature =
    reinterpret_cast<WGPUProcInstanceHasWGSLLanguageFeature>(
      getProcAddress(WGPUStringView{ "wgpuInstanceHasWGSLLanguageFeature", WGPU_STRLEN }));
  if (resolved.InstanceHasWGSLLanguageFeature == nullptr)
  {
    return "wgpuInstanceHasWGSLLanguageFeature";
  }
  resolved.InstanceProcessEvents = reinterpret_cast<WGPUProcInstanceProcessEvents>(
    getProcAddress(WGPUStringView{ "wgpuInstanceProcessEvents", WGPU_STRLEN }));
  if (resolved.InstanceProcessEvents == nullptr)
  {
    return "wgpuInstanceProcessEvents";
  }
  resolved.InstanceRequestAdapter = reinterpret_cast<WGPUProcInstanceRequestAdapter>(
    getProcAddress(WGPUStringView{ "wgpuInstanceRequestAdapter", WGPU_STRLEN }));
  if (resolved.InstanceRequestAdapter == nullptr)
  {
    return "wgpuInstanceRequestAdapter";
  }
  resolved.InstanceWaitAny = reinterpret_cast<WGPUProcInstanceWaitAny>(
    getProcAddress(WGPUStringView{ "wgpuInstanceWaitAny", WGPU_STRLEN }));
  if (resolved.InstanceWaitAny == nullptr)
  {
    return "wgpuInstanceWaitAny";
  }
  resolved.InstanceAddRef = reinterpret_cast<WGPUProcInstanceAddRef>(
    getProcAddress(WGPUStringView{ "wgpuInstanceAddRef", WGPU_STRLEN }));
  if (resolved.InstanceAddRef == nullptr)
  {
    return "wgpuInstanceAddRef";
  }
  resolved.InstanceRelease = reinterpret_cast<WGPUProcInstanceRelease>(
    getProcAddress(WGPUStringView{ "wgpuInstanceRelease", WGPU_STRLEN }));
  if (resolved.InstanceRelease == nullptr)
  {
    return "wgpuInstanceRelease";
  }
  resolved.PipelineLayoutSetLabel = reinterpret_cast<WGPUProcPipelineLayoutSetLabel>(
    getProcAddress(WGPUStringView{ "wgpuPipelineLayoutSetLabel", WGPU_STRLEN }));
  if (resolved.PipelineLayoutSetLabel == nullptr)
  {
    return "wgpuPipelineLayoutSetLabel";
  }
  resolved.PipelineLayoutAddRef = reinterpret_cast<WGPUProcPipelineLayoutAddRef>(
    getProcAddress(WGPUStringView{ "wgpuPipelineLayoutAddRef", WGPU_STRLEN }));
  if (resolved.PipelineLayoutAddRef == nullptr)
  {
    return "wgpuPipelineLayoutAddRef";
  }
  resolved.PipelineLayoutRelease = reinterpret_cast<WGPUProcPipelineLayoutRelease>(
    getProcAddress(WGPUStringView{ "wgpuPipelineLayoutRelease", WGPU_STRLEN }));
  if (resolved.PipelineLayoutRelease == nullptr)
  {
    return "wgpuPipelineLayoutRelease";
  }
  resolved.QuerySetDestroy = reinterpret_cast<WGPUProcQuerySetDestroy>(
    getProcAddress(WGPUStringView{ "wgpuQuerySetDestroy", WGPU_STRLEN }));
  if (resolved.QuerySetDestroy == nullptr)
  {
    return "wgpuQuerySetDestroy";
  }
  resolved.QuerySetGetCount = reinterpret_cast<WGPUProcQuerySetGetCount>(
    getProcAddress(WGPUStringView{ "wgpuQuerySetGetCount", WGPU_STRLEN }));
  if (resolved.QuerySetGetCount == nullptr)
  {
    return "wgpuQuerySetGetCount";
  }
  resolved.QuerySetGetType = reinterpret_cast<WGPUProcQuerySetGetType>(
    getProcAddress(WGPUStringView{ "wgpuQuerySetGetType", WGPU_STRLEN }));
  if (resolved.QuerySetGetType == nullptr)
  {
    return "wgpuQuerySetGetType";
  }
  resolved.QuerySetSetLabel = reinterpret_cast<WGPUProcQuerySetSetLabel>(
    getProcAddress(WGPUStringView{ "wgpuQuerySetSetLabel", WGPU_STRLEN }));
  if (resolved.QuerySetSetLabel == nullptr)
  {
    return "wgpuQuerySetSetLabel";
  }
  resolved.QuerySetAddRef = reinterpret_cast<WGPUProcQuerySetAddRef>(
    getProcAddress(WGPUStringView{ "wgpuQuerySetAddRef", WGPU_STRLEN }));
  if (resolved.QuerySetAddRef == nullptr)
  {
    return "wgpuQuerySetAddRef";
  }
  resolved.QuerySetRelease = reinterpret_cast<WGPUProcQuerySetRelease>(
    getProcAddress(WGPUStringView{ "wgpuQuerySetRelease", WGPU_STRLEN }));
  if (resolved.QuerySetRelease == nullptr)
  {
    return "wgpuQuerySetRelease";
  }
  resolved.QueueOnSubmittedWorkDone = reinterpret_cast<WGPUProcQueueOnSubmittedWorkDone>(
    getProcAddress(WGPUStringView{ "wgpuQueueOnSubmittedWorkDone", WGPU_STRLEN }));
  if (resolved.QueueOnSubmittedWorkDone == nullptr)
  {
    return "wgpuQueueOnSubmittedWorkDone";
  }
  resolved.QueueSetLabel = reinterpret_cast<WGPUProcQueueSetLabel>(
    getProcAddress(WGPUStringView{ "wgpuQueueSetLabel", WGPU_STRLEN }));
  if (resolved.QueueSetLabel == nullptr)
  {
    return "wgpuQueueSetLabel";
  }
  resolved.QueueSubmit = reinterpret_cast<WGPUProcQueueSubmit>(
    getProcAddress(WGPUStringView{ "wgpuQueueSubmit", WGPU_STRLEN }));
  if (resolved.QueueSubmit == nullptr)
  {
    return "wgpuQueueSubmit";
  }
  resolved.QueueWriteBuffer = reinterpret_cast<WGPUProcQueueWriteBuffer>(
    getProcAddress(WGPUStringView{ "wgpuQueueWriteBuffer", WGPU_STRLEN }));
  if (resolved.QueueWriteBuffer == nullptr)
  {
    return "wgpuQueueWriteBuffer";
  }
  resolved.QueueWriteTexture = reinterpret_cast<WGPUProcQueueWriteTexture>(
    getProcAddress(WGPUStringView{ "wgpuQueueWriteTexture", WGPU_STRLEN }));
  if (resolved.QueueWriteTexture == nullptr)
  {
    return "wgpuQueueWriteTexture";
  }
  resolved.QueueAddRef = reinterpret_cast<WGPUProcQueueAddRef>(
    getProcAddress(WGPUStringView{ "wgpuQueueAddRef", WGPU_STRLEN }));
  if (resolved.QueueAddRef == nullptr)
  {
    return "wgpuQueueAddRef";
  }
  resolved.QueueRelease = reinterpret_cast<WGPUProcQueueRelease>(
    getProcAddress(WGPUStringView{ "wgpuQueueRelease", WGPU_STRLEN }));
  if (resolved.QueueRelease == nullptr)
  {
    return "wgpuQueueRelease";
  }
  resolved.RenderBundleSetLabel = reinterpret_cast<WGPUProcRenderBundleSetLabel>(
    getProcAddress(WGPUStringView{ "wgpuRenderBundleSetLabel", WGPU_STRLEN }));
  if (resolved.RenderBundleSetLabel == nullptr)
  {
    return "wgpuRenderBundleSetLabel";
  }
  resolved.RenderBundleAddRef = reinterpret_cast<WGPUProcRenderBundleAddRef>(
    getProcAddress(WGPUStringView{ "wgpuRenderBundleAddRef", WGPU_STRLEN }));
  if (resolved.RenderBundleAddRef == nullptr)
  {
    return "wgpuRenderBundleAddRef";
  }
  resolved.RenderBundleRelease = reinterpret_cast<WGPUProcRenderBundleRelease>(
    getProcAddress(WGPUStringView{ "wgpuRenderBundleRelease", WGPU_STRLEN }));
  if (resolved.RenderBundleRelease == nullptr)
  {
    return "wgpuRenderBundleRelease";
  }
  resolved.RenderBundleEncoderDraw = reinterpret_cast<WGPUProcRenderBundleEncoderDraw>(
    getProcAddress(WGPUStringView{ "wgpuRenderBundleEncoderDraw", WGPU_STRLEN }));
  if (resolved.RenderBundleEncoderDraw == nullptr)
  {
    return "wgpuRenderBundleEncoderDraw";
  }
  resolved.RenderBundleEncoderDrawIndexed =
    reinterpret_cast<WGPUProcRenderBundleEncoderDrawIndexed>(
      getProcAddress(WGPUStringView{ "wgpuRenderBundleEncoderDrawIndexed", WGPU_STRLEN }));
  if (resolved.RenderBundleEncoderDrawIndexed == nullptr)
  {
    return "wgpuRenderBundleEncoderDrawIndexed";
  }
  resolved.RenderBundleEncoderDrawIndexedIndirect =
    reinterpret_cast<WGPUProcRenderBundleEncoderDrawIndexedIndirect>(
      getProcAddress(WGPUStringView{ "wgpuRenderBundleEncoderDrawIndexedIndirect", WGPU_STRLEN }));
  if (resolved.RenderBundleEncoderDrawIndexedIndirect == nullptr)
  {
    return "wgpuRenderBundleEncoderDrawIndexedIndirect";
  }
  resolved.RenderBundleEncoderDrawIndirect =
    reinterpret_cast<WGPUProcRenderBundleEncoderDrawIndirect>(
      getProcAddress(WGPUStringView{ "wgpuRenderBundleEncoderDrawIndirect", WGPU_STRLEN }));
  if (resolved.RenderBundleEncoderDrawIndirect == nullptr)
  {
    return "wgpuRenderBundleEncoderDrawIndirect";
  }
  resolved.RenderBundleEncoderFinish = reinterpret_cast<WGPUProcRenderBundleEncoderFinish>(
    getProcAddress(WGPUStringView{ "wgpuRenderBundleEncoderFinish", WGPU_STRLEN }));
  if (resolved.RenderBundleEncoderFinish == nullptr)
  {
    return "wgpuRenderBundleEncoderFinish";
  }
  resolved.RenderBundleEncoderInsertDebugMarker =
    reinterpret_cast<WGPUProcRenderBundleEncoderInsertDebugMarker>(
      getProcAddress(WGPUStringView{ "wgpuRenderBundleEncoderInsertDebugMarker", WGPU_STRLEN }));
  if (resolved.RenderBundleEncoderInsertDebugMarker == nullptr)
  {
    return "wgpuRenderBundleEncoderInsertDebugMarker";
  }
  resolved.RenderBundleEncoderPopDebugGroup =
    reinterpret_cast<WGPUProcRenderBundleEncoderPopDebugGroup>(
      getProcAddress(WGPUStringView{ "wgpuRenderBundleEncoderPopDebugGroup", WGPU_STRLEN }));
  if (resolved.RenderBundleEncoderPopDebugGroup == nullptr)
  {
    return "wgpuRenderBundleEncoderPopDebugGroup";
  }
  resolved.RenderBundleEncoderPushDebugGroup =
    reinterpret_cast<WGPUProcRenderBundleEncoderPushDebugGroup>(
      getProcAddress(WGPUStringView{ "wgpuRenderBundleEncoderPushDebugGroup", WGPU_STRLEN }));
  if (resolved.RenderBundleEncoderPushDebugGroup == nullptr)
  {
    return "wgpuRenderBundleEncoderPushDebugGroup";
  }
  resolved.RenderBundleEncoderSetBindGroup =
    reinterpret_cast<WGPUProcRenderBundleEncoderSetBindGroup>(
      getProcAddress(WGPUStringView{ "wgpuRenderBundleEncoderSetBindGroup", WGPU_STRLEN }));
  if (resolved.RenderBundleEncoderSetBindGroup == nullptr)
  {
    return "wgpuRenderBundleEncoderSetBindGroup";
  }
  resolved.RenderBundleEncoderSetImmediates =
    reinterpret_cast<WGPUProcRenderBundleEncoderSetImmediates>(
      getProcAddress(WGPUStringView{ "wgpuRenderBundleEncoderSetImmediates", WGPU_STRLEN }));
  if (resolved.RenderBundleEncoderSetImmediates == nullptr)
  {
    return "wgpuRenderBundleEncoderSetImmediates";
  }
  resolved.RenderBundleEncoderSetIndexBuffer =
    reinterpret_cast<WGPUProcRenderBundleEncoderSetIndexBuffer>(
      getProcAddress(WGPUStringView{ "wgpuRenderBundleEncoderSetIndexBuffer", WGPU_STRLEN }));
  if (resolved.RenderBundleEncoderSetIndexBuffer == nullptr)
  {
    return "wgpuRenderBundleEncoderSetIndexBuffer";
  }
  resolved.RenderBundleEncoderSetLabel = reinterpret_cast<WGPUProcRenderBundleEncoderSetLabel>(
    getProcAddress(WGPUStringView{ "wgpuRenderBundleEncoderSetLabel", WGPU_STRLEN }));
  if (resolved.RenderBundleEncoderSetLabel == nullptr)
  {
    return "wgpuRenderBundleEncoderSetLabel";
  }
  resolved.RenderBundleEncoderSetPipeline =
    reinterpret_cast<WGPUProcRenderBundleEncoderSetPipeline>(
      getProcAddress(WGPUStringView{ "wgpuRenderBundleEncoderSetPipeline", WGPU_STRLEN }));
  if (resolved.RenderBundleEncoderSetPipeline == nullptr)
  {
    return "wgpuRenderBundleEncoderSetPipeline";
  }
  resolved.RenderBundleEncoderSetVertexBuffer =
    reinterpret_cast<WGPUProcRenderBundleEncoderSetVertexBuffer>(
      getProcAddress(WGPUStringView{ "wgpuRenderBundleEncoderSetVertexBuffer", WGPU_STRLEN }));
  if (resolved.RenderBundleEncoderSetVertexBuffer == nullptr)
  {
    return "wgpuRenderBundleEncoderSetVertexBuffer";
  }
  resolved.RenderBundleEncoderAddRef = reinterpret_cast<WGPUProcRenderBundleEncoderAddRef>(
    getProcAddress(WGPUStringView{ "wgpuRenderBundleEncoderAddRef", WGPU_STRLEN }));
  if (resolved.RenderBundleEncoderAddRef == nullptr)
  {
    return "wgpuRenderBundleEncoderAddRef";
  }
  resolved.RenderBundleEncoderRelease = reinterpret_cast<WGPUProcRenderBundleEncoderRelease>(
    getProcAddress(WGPUStringView{ "wgpuRenderBundleEncoderRelease", WGPU_STRLEN }));
  if (resolved.RenderBundleEncoderRelease == nullptr)
  {
    return "wgpuRenderBundleEncoderRelease";
  }
  resolved.RenderPassEncoderBeginOcclusionQuery =
    reinterpret_cast<WGPUProcRenderPassEncoderBeginOcclusionQuery>(
      getProcAddress(WGPUStringView{ "wgpuRenderPassEncoderBeginOcclusionQuery", WGPU_STRLEN }));
  if (resolved.RenderPassEncoderBeginOcclusionQuery == nullptr)
  {
    return "wgpuRenderPassEncoderBeginOcclusionQuery";
  }
  resolved.RenderPassEncoderDraw = reinterpret_cast<WGPUProcRenderPassEncoderDraw>(
    getProcAddress(WGPUStringView{ "wgpuRenderPassEncoderDraw", WGPU_STRLEN }));
  if (resolved.RenderPassEncoderDraw == nullptr)
  {
    return "wgpuRenderPassEncoderDraw";
  }
  resolved.RenderPassEncoderDrawIndexed = reinterpret_cast<WGPUProcRenderPassEncoderDrawIndexed>(
    getProcAddress(WGPUStringView{ "wgpuRenderPassEncoderDrawIndexed", WGPU_STRLEN }));
  if (resolved.RenderPassEncoderDrawIndexed == nullptr)
  {
    return "wgpuRenderPassEncoderDrawIndexed";
  }
  resolved.RenderPassEncoderDrawIndexedIndirect =
    reinterpret_cast<WGPUProcRenderPassEncoderDrawIndexedIndirect>(
      getProcAddress(WGPUStringView{ "wgpuRenderPassEncoderDrawIndexedIndirect", WGPU_STRLEN }));
  if (resolved.RenderPassEncoderDrawIndexedIndirect == nullptr)
  {
    return "wgpuRenderPassEncoderDrawIndexedIndirect";
  }
  resolved.RenderPassEncoderDrawIndirect = reinterpret_cast<WGPUProcRenderPassEncoderDrawIndirect>(
    getProcAddress(WGPUStringView{ "wgpuRenderPassEncoderDrawIndirect", WGPU_STRLEN }));
  if (resolved.RenderPassEncoderDrawIndirect == nullptr)
  {
    return "wgpuRenderPassEncoderDrawIndirect";
  }
  resolved.RenderPassEncoderEnd = reinterpret_cast<WGPUProcRenderPassEncoderEnd>(
    getProcAddress(WGPUStringView{ "wgpuRenderPassEncoderEnd", WGPU_STRLEN }));
  if (resolved.RenderPassEncoderEnd == nullptr)
  {
    return "wgpuRenderPassEncoderEnd";
  }
  resolved.RenderPassEncoderEndOcclusionQuery =
    reinterpret_cast<WGPUProcRenderPassEncoderEndOcclusionQuery>(
      getProcAddress(WGPUStringView{ "wgpuRenderPassEncoderEndOcclusionQuery", WGPU_STRLEN }));
  if (resolved.RenderPassEncoderEndOcclusionQuery == nullptr)
  {
    return "wgpuRenderPassEncoderEndOcclusionQuery";
  }
  resolved.RenderPassEncoderExecuteBundles =
    reinterpret_cast<WGPUProcRenderPassEncoderExecuteBundles>(
      getProcAddress(WGPUStringView{ "wgpuRenderPassEncoderExecuteBundles", WGPU_STRLEN }));
  if (resolved.RenderPassEncoderExecuteBundles == nullptr)
  {
    return "wgpuRenderPassEncoderExecuteBundles";
  }
  resolved.RenderPassEncoderInsertDebugMarker =
    reinterpret_cast<WGPUProcRenderPassEncoderInsertDebugMarker>(
      getProcAddress(WGPUStringView{ "wgpuRenderPassEncoderInsertDebugMarker", WGPU_STRLEN }));
  if (resolved.RenderPassEncoderInsertDebugMarker == nullptr)
  {
    return "wgpuRenderPassEncoderInsertDebugMarker";
  }
  resolved.RenderPassEncoderPopDebugGroup =
    reinterpret_cast<WGPUProcRenderPassEncoderPopDebugGroup>(
      getProcAddress(WGPUStringView{ "wgpuRenderPassEncoderPopDebugGroup", WGPU_STRLEN }));
  if (resolved.RenderPassEncoderPopDebugGroup == nullptr)
  {
    return "wgpuRenderPassEncoderPopDebugGroup";
  }
  resolved.RenderPassEncoderPushDebugGroup =
    reinterpret_cast<WGPUProcRenderPassEncoderPushDebugGroup>(
      getProcAddress(WGPUStringView{ "wgpuRenderPassEncoderPushDebugGroup", WGPU_STRLEN }));
  if (resolved.RenderPassEncoderPushDebugGroup == nullptr)
  {
    return "wgpuRenderPassEncoderPushDebugGroup";
  }
  resolved.RenderPassEncoderSetBindGroup = reinterpret_cast<WGPUProcRenderPassEncoderSetBindGroup>(
    getProcAddress(WGPUStringView{ "wgpuRenderPassEncoderSetBindGroup", WGPU_STRLEN }));
  if (resolved.RenderPassEncoderSetBindGroup == nullptr)
  {
    return "wgpuRenderPassEncoderSetBindGroup";
  }
  resolved.RenderPassEncoderSetBlendConstant =
    reinterpret_cast<WGPUProcRenderPassEncoderSetBlendConstant>(
      getProcAddress(WGPUStringView{ "wgpuRenderPassEncoderSetBlendConstant", WGPU_STRLEN }));
  if (resolved.RenderPassEncoderSetBlendConstant == nullptr)
  {
    return "wgpuRenderPassEncoderSetBlendConstant";
  }
  resolved.RenderPassEncoderSetImmediates =
    reinterpret_cast<WGPUProcRenderPassEncoderSetImmediates>(
      getProcAddress(WGPUStringView{ "wgpuRenderPassEncoderSetImmediates", WGPU_STRLEN }));
  if (resolved.RenderPassEncoderSetImmediates == nullptr)
  {
    return "wgpuRenderPassEncoderSetImmediates";
  }
  resolved.RenderPassEncoderSetIndexBuffer =
    reinterpret_cast<WGPUProcRenderPassEncoderSetIndexBuffer>(
      getProcAddress(WGPUStringView{ "wgpuRenderPassEncoderSetIndexBuffer", WGPU_STRLEN }));
  if (resolved.RenderPassEncoderSetIndexBuffer == nullptr)
  {
    return "wgpuRenderPassEncoderSetIndexBuffer";
  }
  resolved.RenderPassEncoderSetLabel = reinterpret_cast<WGPUProcRenderPassEncoderSetLabel>(
    getProcAddress(WGPUStringView{ "wgpuRenderPassEncoderSetLabel", WGPU_STRLEN }));
  if (resolved.RenderPassEncoderSetLabel == nullptr)
  {
    return "wgpuRenderPassEncoderSetLabel";
  }
  resolved.RenderPassEncoderSetPipeline = reinterpret_cast<WGPUProcRenderPassEncoderSetPipeline>(
    getProcAddress(WGPUStringView{ "wgpuRenderPassEncoderSetPipeline", WGPU_STRLEN }));
  if (resolved.RenderPassEncoderSetPipeline == nullptr)
  {
    return "wgpuRenderPassEncoderSetPipeline";
  }
  resolved.RenderPassEncoderSetScissorRect =
    reinterpret_cast<WGPUProcRenderPassEncoderSetScissorRect>(
      getProcAddress(WGPUStringView{ "wgpuRenderPassEncoderSetScissorRect", WGPU_STRLEN }));
  if (resolved.RenderPassEncoderSetScissorRect == nullptr)
  {
    return "wgpuRenderPassEncoderSetScissorRect";
  }
  resolved.RenderPassEncoderSetStencilReference =
    reinterpret_cast<WGPUProcRenderPassEncoderSetStencilReference>(
      getProcAddress(WGPUStringView{ "wgpuRenderPassEncoderSetStencilReference", WGPU_STRLEN }));
  if (resolved.RenderPassEncoderSetStencilReference == nullptr)
  {
    return "wgpuRenderPassEncoderSetStencilReference";
  }
  resolved.RenderPassEncoderSetVertexBuffer =
    reinterpret_cast<WGPUProcRenderPassEncoderSetVertexBuffer>(
      getProcAddress(WGPUStringView{ "wgpuRenderPassEncoderSetVertexBuffer", WGPU_STRLEN }));
  if (resolved.RenderPassEncoderSetVertexBuffer == nullptr)
  {
    return "wgpuRenderPassEncoderSetVertexBuffer";
  }
  resolved.RenderPassEncoderSetViewport = reinterpret_cast<WGPUProcRenderPassEncoderSetViewport>(
    getProcAddress(WGPUStringView{ "wgpuRenderPassEncoderSetViewport", WGPU_STRLEN }));
  if (resolved.RenderPassEncoderSetViewport == nullptr)
  {
    return "wgpuRenderPassEncoderSetViewport";
  }
  resolved.RenderPassEncoderAddRef = reinterpret_cast<WGPUProcRenderPassEncoderAddRef>(
    getProcAddress(WGPUStringView{ "wgpuRenderPassEncoderAddRef", WGPU_STRLEN }));
  if (resolved.RenderPassEncoderAddRef == nullptr)
  {
    return "wgpuRenderPassEncoderAddRef";
  }
  resolved.RenderPassEncoderRelease = reinterpret_cast<WGPUProcRenderPassEncoderRelease>(
    getProcAddress(WGPUStringView{ "wgpuRenderPassEncoderRelease", WGPU_STRLEN }));
  if (resolved.RenderPassEncoderRelease == nullptr)
  {
    return "wgpuRenderPassEncoderRelease";
  }
  resolved.RenderPipelineGetBindGroupLayout =
    reinterpret_cast<WGPUProcRenderPipelineGetBindGroupLayout>(
      getProcAddress(WGPUStringView{ "wgpuRenderPipelineGetBindGroupLayout", WGPU_STRLEN }));
  if (resolved.RenderPipelineGetBindGroupLayout == nullptr)
  {
    return "wgpuRenderPipelineGetBindGroupLayout";
  }
  resolved.RenderPipelineSetLabel = reinterpret_cast<WGPUProcRenderPipelineSetLabel>(
    getProcAddress(WGPUStringView{ "wgpuRenderPipelineSetLabel", WGPU_STRLEN }));
  if (resolved.RenderPipelineSetLabel == nullptr)
  {
    return "wgpuRenderPipelineSetLabel";
  }
  resolved.RenderPipelineAddRef = reinterpret_cast<WGPUProcRenderPipelineAddRef>(
    getProcAddress(WGPUStringView{ "wgpuRenderPipelineAddRef", WGPU_STRLEN }));
  if (resolved.RenderPipelineAddRef == nullptr)
  {
    return "wgpuRenderPipelineAddRef";
  }
  resolved.RenderPipelineRelease = reinterpret_cast<WGPUProcRenderPipelineRelease>(
    getProcAddress(WGPUStringView{ "wgpuRenderPipelineRelease", WGPU_STRLEN }));
  if (resolved.RenderPipelineRelease == nullptr)
  {
    return "wgpuRenderPipelineRelease";
  }
  resolved.SamplerSetLabel = reinterpret_cast<WGPUProcSamplerSetLabel>(
    getProcAddress(WGPUStringView{ "wgpuSamplerSetLabel", WGPU_STRLEN }));
  if (resolved.SamplerSetLabel == nullptr)
  {
    return "wgpuSamplerSetLabel";
  }
  resolved.SamplerAddRef = reinterpret_cast<WGPUProcSamplerAddRef>(
    getProcAddress(WGPUStringView{ "wgpuSamplerAddRef", WGPU_STRLEN }));
  if (resolved.SamplerAddRef == nullptr)
  {
    return "wgpuSamplerAddRef";
  }
  resolved.SamplerRelease = reinterpret_cast<WGPUProcSamplerRelease>(
    getProcAddress(WGPUStringView{ "wgpuSamplerRelease", WGPU_STRLEN }));
  if (resolved.SamplerRelease == nullptr)
  {
    return "wgpuSamplerRelease";
  }
  resolved.ShaderModuleGetCompilationInfo =
    reinterpret_cast<WGPUProcShaderModuleGetCompilationInfo>(
      getProcAddress(WGPUStringView{ "wgpuShaderModuleGetCompilationInfo", WGPU_STRLEN }));
  if (resolved.ShaderModuleGetCompilationInfo == nullptr)
  {
    return "wgpuShaderModuleGetCompilationInfo";
  }
  resolved.ShaderModuleSetLabel = reinterpret_cast<WGPUProcShaderModuleSetLabel>(
    getProcAddress(WGPUStringView{ "wgpuShaderModuleSetLabel", WGPU_STRLEN }));
  if (resolved.ShaderModuleSetLabel == nullptr)
  {
    return "wgpuShaderModuleSetLabel";
  }
  resolved.ShaderModuleAddRef = reinterpret_cast<WGPUProcShaderModuleAddRef>(
    getProcAddress(WGPUStringView{ "wgpuShaderModuleAddRef", WGPU_STRLEN }));
  if (resolved.ShaderModuleAddRef == nullptr)
  {
    return "wgpuShaderModuleAddRef";
  }
  resolved.ShaderModuleRelease = reinterpret_cast<WGPUProcShaderModuleRelease>(
    getProcAddress(WGPUStringView{ "wgpuShaderModuleRelease", WGPU_STRLEN }));
  if (resolved.ShaderModuleRelease == nullptr)
  {
    return "wgpuShaderModuleRelease";
  }
  resolved.SupportedFeaturesFreeMembers = reinterpret_cast<WGPUProcSupportedFeaturesFreeMembers>(
    getProcAddress(WGPUStringView{ "wgpuSupportedFeaturesFreeMembers", WGPU_STRLEN }));
  if (resolved.SupportedFeaturesFreeMembers == nullptr)
  {
    return "wgpuSupportedFeaturesFreeMembers";
  }
  resolved.SupportedInstanceFeaturesFreeMembers =
    reinterpret_cast<WGPUProcSupportedInstanceFeaturesFreeMembers>(
      getProcAddress(WGPUStringView{ "wgpuSupportedInstanceFeaturesFreeMembers", WGPU_STRLEN }));
  if (resolved.SupportedInstanceFeaturesFreeMembers == nullptr)
  {
    return "wgpuSupportedInstanceFeaturesFreeMembers";
  }
  resolved.SupportedWGSLLanguageFeaturesFreeMembers =
    reinterpret_cast<WGPUProcSupportedWGSLLanguageFeaturesFreeMembers>(getProcAddress(
      WGPUStringView{ "wgpuSupportedWGSLLanguageFeaturesFreeMembers", WGPU_STRLEN }));
  if (resolved.SupportedWGSLLanguageFeaturesFreeMembers == nullptr)
  {
    return "wgpuSupportedWGSLLanguageFeaturesFreeMembers";
  }
  resolved.SurfaceConfigure = reinterpret_cast<WGPUProcSurfaceConfigure>(
    getProcAddress(WGPUStringView{ "wgpuSurfaceConfigure", WGPU_STRLEN }));
  if (resolved.SurfaceConfigure == nullptr)
  {
    return "wgpuSurfaceConfigure";
  }
  resolved.SurfaceGetCapabilities = reinterpret_cast<WGPUProcSurfaceGetCapabilities>(
    getProcAddress(WGPUStringView{ "wgpuSurfaceGetCapabilities", WGPU_STRLEN }));
  if (resolved.SurfaceGetCapabilities == nullptr)
  {
    return "wgpuSurfaceGetCapabilities";
  }
  resolved.SurfaceGetCurrentTexture = reinterpret_cast<WGPUProcSurfaceGetCurrentTexture>(
    getProcAddress(WGPUStringView{ "wgpuSurfaceGetCurrentTexture", WGPU_STRLEN }));
  if (resolved.SurfaceGetCurrentTexture == nullptr)
  {
    return "wgpuSurfaceGetCurrentTexture";
  }
  resolved.SurfacePresent = reinterpret_cast<WGPUProcSurfacePresent>(
    getProcAddress(WGPUStringView{ "wgpuSurfacePresent", WGPU_STRLEN }));
  if (resolved.SurfacePresent == nullptr)
  {
    return "wgpuSurfacePresent";
  }
  resolved.SurfaceSetLabel = reinterpret_cast<WGPUProcSurfaceSetLabel>(
    getProcAddress(WGPUStringView{ "wgpuSurfaceSetLabel", WGPU_STRLEN }));
  if (resolved.SurfaceSetLabel == nullptr)
  {
    return "wgpuSurfaceSetLabel";
  }
  resolved.SurfaceUnconfigure = reinterpret_cast<WGPUProcSurfaceUnconfigure>(
    getProcAddress(WGPUStringView{ "wgpuSurfaceUnconfigure", WGPU_STRLEN }));
  if (resolved.SurfaceUnconfigure == nullptr)
  {
    return "wgpuSurfaceUnconfigure";
  }
  resolved.SurfaceAddRef = reinterpret_cast<WGPUProcSurfaceAddRef>(
    getProcAddress(WGPUStringView{ "wgpuSurfaceAddRef", WGPU_STRLEN }));
  if (resolved.SurfaceAddRef == nullptr)
  {
    return "wgpuSurfaceAddRef";
  }
  resolved.SurfaceRelease = reinterpret_cast<WGPUProcSurfaceRelease>(
    getProcAddress(WGPUStringView{ "wgpuSurfaceRelease", WGPU_STRLEN }));
  if (resolved.SurfaceRelease == nullptr)
  {
    return "wgpuSurfaceRelease";
  }
  resolved.SurfaceCapabilitiesFreeMembers =
    reinterpret_cast<WGPUProcSurfaceCapabilitiesFreeMembers>(
      getProcAddress(WGPUStringView{ "wgpuSurfaceCapabilitiesFreeMembers", WGPU_STRLEN }));
  if (resolved.SurfaceCapabilitiesFreeMembers == nullptr)
  {
    return "wgpuSurfaceCapabilitiesFreeMembers";
  }
  resolved.TextureCreateView = reinterpret_cast<WGPUProcTextureCreateView>(
    getProcAddress(WGPUStringView{ "wgpuTextureCreateView", WGPU_STRLEN }));
  if (resolved.TextureCreateView == nullptr)
  {
    return "wgpuTextureCreateView";
  }
  resolved.TextureDestroy = reinterpret_cast<WGPUProcTextureDestroy>(
    getProcAddress(WGPUStringView{ "wgpuTextureDestroy", WGPU_STRLEN }));
  if (resolved.TextureDestroy == nullptr)
  {
    return "wgpuTextureDestroy";
  }
  resolved.TextureGetDepthOrArrayLayers = reinterpret_cast<WGPUProcTextureGetDepthOrArrayLayers>(
    getProcAddress(WGPUStringView{ "wgpuTextureGetDepthOrArrayLayers", WGPU_STRLEN }));
  if (resolved.TextureGetDepthOrArrayLayers == nullptr)
  {
    return "wgpuTextureGetDepthOrArrayLayers";
  }
  resolved.TextureGetDimension = reinterpret_cast<WGPUProcTextureGetDimension>(
    getProcAddress(WGPUStringView{ "wgpuTextureGetDimension", WGPU_STRLEN }));
  if (resolved.TextureGetDimension == nullptr)
  {
    return "wgpuTextureGetDimension";
  }
  resolved.TextureGetFormat = reinterpret_cast<WGPUProcTextureGetFormat>(
    getProcAddress(WGPUStringView{ "wgpuTextureGetFormat", WGPU_STRLEN }));
  if (resolved.TextureGetFormat == nullptr)
  {
    return "wgpuTextureGetFormat";
  }
  resolved.TextureGetHeight = reinterpret_cast<WGPUProcTextureGetHeight>(
    getProcAddress(WGPUStringView{ "wgpuTextureGetHeight", WGPU_STRLEN }));
  if (resolved.TextureGetHeight == nullptr)
  {
    return "wgpuTextureGetHeight";
  }
  resolved.TextureGetMipLevelCount = reinterpret_cast<WGPUProcTextureGetMipLevelCount>(
    getProcAddress(WGPUStringView{ "wgpuTextureGetMipLevelCount", WGPU_STRLEN }));
  if (resolved.TextureGetMipLevelCount == nullptr)
  {
    return "wgpuTextureGetMipLevelCount";
  }
  resolved.TextureGetSampleCount = reinterpret_cast<WGPUProcTextureGetSampleCount>(
    getProcAddress(WGPUStringView{ "wgpuTextureGetSampleCount", WGPU_STRLEN }));
  if (resolved.TextureGetSampleCount == nullptr)
  {
    return "wgpuTextureGetSampleCount";
  }
  resolved.TextureGetTextureBindingViewDimension =
    reinterpret_cast<WGPUProcTextureGetTextureBindingViewDimension>(
      getProcAddress(WGPUStringView{ "wgpuTextureGetTextureBindingViewDimension", WGPU_STRLEN }));
  if (resolved.TextureGetTextureBindingViewDimension == nullptr)
  {
    return "wgpuTextureGetTextureBindingViewDimension";
  }
  resolved.TextureGetUsage = reinterpret_cast<WGPUProcTextureGetUsage>(
    getProcAddress(WGPUStringView{ "wgpuTextureGetUsage", WGPU_STRLEN }));
  if (resolved.TextureGetUsage == nullptr)
  {
    return "wgpuTextureGetUsage";
  }
  resolved.TextureGetWidth = reinterpret_cast<WGPUProcTextureGetWidth>(
    getProcAddress(WGPUStringView{ "wgpuTextureGetWidth", WGPU_STRLEN }));
  if (resolved.TextureGetWidth == nullptr)
  {
    return "wgpuTextureGetWidth";
  }
  resolved.TextureSetLabel = reinterpret_cast<WGPUProcTextureSetLabel>(
    getProcAddress(WGPUStringView{ "wgpuTextureSetLabel", WGPU_STRLEN }));
  if (resolved.TextureSetLabel == nullptr)
  {
    return "wgpuTextureSetLabel";
  }
  resolved.TextureAddRef = reinterpret_cast<WGPUProcTextureAddRef>(
    getProcAddress(WGPUStringView{ "wgpuTextureAddRef", WGPU_STRLEN }));
  if (resolved.TextureAddRef == nullptr)
  {
    return "wgpuTextureAddRef";
  }
  resolved.TextureRelease = reinterpret_cast<WGPUProcTextureRelease>(
    getProcAddress(WGPUStringView{ "wgpuTextureRelease", WGPU_STRLEN }));
  if (resolved.TextureRelease == nullptr)
  {
    return "wgpuTextureRelease";
  }
  resolved.TextureViewSetLabel = reinterpret_cast<WGPUProcTextureViewSetLabel>(
    getProcAddress(WGPUStringView{ "wgpuTextureViewSetLabel", WGPU_STRLEN }));
  if (resolved.TextureViewSetLabel == nullptr)
  {
    return "wgpuTextureViewSetLabel";
  }
  resolved.TextureViewAddRef = reinterpret_cast<WGPUProcTextureViewAddRef>(
    getProcAddress(WGPUStringView{ "wgpuTextureViewAddRef", WGPU_STRLEN }));
  if (resolved.TextureViewAddRef == nullptr)
  {
    return "wgpuTextureViewAddRef";
  }
  resolved.TextureViewRelease = reinterpret_cast<WGPUProcTextureViewRelease>(
    getProcAddress(WGPUStringView{ "wgpuTextureViewRelease", WGPU_STRLEN }));
  if (resolved.TextureViewRelease == nullptr)
  {
    return "wgpuTextureViewRelease";
  }
  vtkWebGPUProcs = resolved;
  return nullptr;
}
VTK_ABI_NAMESPACE_END

#endif // !__EMSCRIPTEN__
