vtk_module(vtkIOADIOS
  TEST_DEPENDS
    vtkTestingCore
    vtkTestingRendering
  EXCLUDE_FROM_ALL
  DEPENDS
    vtkCommonCore
    vtkCommonExecutionModel
    vtkParallelCore
  PRIVATE_DEPENDS
    vtkCommonDataModel
    vtkParallelMPI
  )