vtk_module(vtkRenderingFreeType
  IMPLEMENTS
    vtkRenderingCore
  GROUPS
    Rendering
  DEPENDS
    vtkRenderingCore
    vtkfreetype
    vtkftgl
  TEST_DEPENDS
    vtkTestingRendering
    vtkViewsContext2D
  )
