vtk_module(vtkFiltersSelection
  GROUPS
    StandAlone
  DEPENDS
    vtkCommonComputationalGeometry
    vtkFiltersCore
  TEST_DEPENDS
    vtkFiltersExtraction
    vtkIOLegacy
    vtkIOXML
    vtkRenderingOpenGL2
    vtkRenderingFreeTypeOpenGL
    vtkRenderingAnnotation
    vtkTestingRendering
    vtkInteractionStyle
  )
