if (NOT WIN32)
  vtk_module(vtkFiltersParallelDIY2
    IMPLEMENTS
      vtkFiltersCore
      vtkFiltersParallel
    GROUPS
      MPI
    TEST_DEPENDS
      vtkFiltersParallelMPI
      vtkInteractionStyle
      vtkRenderingOpenGL2
      vtkRenderingParallel
      vtkTestingCore
      vtkTestingRendering
    KIT
      vtkParallel
    DEPENDS
      vtkFiltersCore
      vtkFiltersParallel
      vtkImagingCore
      vtkdiy2
    PRIVATE_DEPENDS
      vtkCommonCore
      vtkCommonDataModel
      vtkCommonExecutionModel
      vtkIOXML
      vtkParallelMPI
    )
endif()
