vtk_module(vtkIOParallelLSDyna
  TEST_DEPENDS
    vtkParallelMPI
    vtkRenderingParallel
    vtkTestingRendering
    vtkInteractionStyle
    vtkRendering${VTK_RENDERING_BACKEND}
  KIT
    vtkParallel
  DEPENDS
    vtkIOLSDyna
  PRIVATE_DEPENDS
    vtkCommonCore
    vtkCommonDataModel
    vtkCommonExecutionModel
    vtkParallelCore
  )