NAME
  VTK::FiltersDSP
LIBRARY_NAME
  vtkFiltersDSP
DESCRIPTION
  Digital Signal Processing module
KIT
  VTK::Filters
GROUPS
  StandAlone
SPDX_LICENSE_IDENTIFIER
  BSD-3-Clause
SPDX_COPYRIGHT_TEXT
  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
DEPENDS
  VTK::CommonCore
  VTK::CommonDataModel
  VTK::CommonExecutionModel
  VTK::FiltersGeneral
PRIVATE_DEPENDS
  VTK::CommonMath
TEST_DEPENDS
  VTK::TestingCore
