vtk_module(vtkFiltersTexture
  GROUPS
    StandAlone
  TEST_DEPENDS
    vtkRenderingOpenGL2
  KIT
    vtkFilters
  DEPENDS
    vtkCommonExecutionModel
  PRIVATE_DEPENDS
    vtkCommonCore
    vtkCommonDataModel
    vtkCommonTransforms
    vtkFiltersGeneral
  )
