vtk_module(vtkFiltersTexture
  GROUPS
    StandAlone
  TEST_DEPENDS
    vtkImagingCore
    vtkIOGeometry
    vtkIOXML
    vtkRenderingCore
    vtkRenderingOpenGL2
    vtkTestingCore
    vtkTestingRendering
  KIT
    vtkFilters
  DEPENDS
    vtkCommonExecutionModel
  PRIVATE_DEPENDS
    vtkCommonCore
    vtkCommonDataModel
    vtkCommonTransforms
    vtkFiltersGeneral
  )
