vtk_module(vtkIOSegY
  TEST_DEPENDS
    vtkInteractionStyle
    vtkRenderingOpenGL2
    vtkTestingCore
    vtkTestingRendering
  KIT
    vtkIO
  DEPENDS
    vtkCommonDataModel
    vtkCommonExecutionModel
    vtkIOImage
  PRIVATE_DEPENDS
    vtkCommonCore
  )
