vtk_module(vtkIOMPIParallel
  IMPLEMENTS
    vtkIOGeometry
    vtkIOParallel
  GROUPS
    MPI
  TEST_DEPENDS
    vtkRenderingOpenGL2
    vtkTestingRendering
    vtkInteractionStyle
  KIT
    vtkParallel
  DEPENDS
    vtkIOGeometry
    vtkIOParallel
  PRIVATE_DEPENDS
    vtkCommonCore
    vtkCommonDataModel
    vtkCommonExecutionModel
    vtkCommonMisc
    vtkParallelMPI
    vtksys
  )
