vtk_module(vtkIOPLY
  GROUPS
    StandAlone
  DEPENDS
    vtkCommonMisc
    vtkCommonExecutionModel
    vtkIOGeometry
  TEST_DEPENDS
    vtkRendering${VTK_RENDERING_BACKEND}
    vtkIOImage
    vtkTestingRendering
    vtkInteractionStyle
  KIT
    vtkIO
  )
