NAME
  VTK::IOPLY
LIBRARY_NAME
  vtkIOPLY
LICENSE_FILES
  Copyright.txt
KIT
  VTK::IO
GROUPS
  StandAlone
SPDX_LICENSE_IDENTIFIER
  BSD-3-Clause AND MIT
SPDX_COPYRIGHT_TEXT
  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
  Copyright (c) 1994 The Board of Trustees of The Leland Stanford
DEPENDS
  VTK::CommonCore
  VTK::IOCore
PRIVATE_DEPENDS
  VTK::CommonDataModel
  VTK::CommonMisc
  VTK::vtksys
TEST_DEPENDS
  VTK::FiltersSources
  VTK::IOImage
  VTK::InteractionStyle
  VTK::RenderingOpenGL2
  VTK::TestingRendering
