vtk_module(vtkIOExportPDF
  GROUPS
    Rendering
  IMPLEMENTS
    vtkIOExport
  TEST_DEPENDS
    vtkChartsCore
    vtkTestingRendering
    vtkRenderingContextOpenGL2
    vtkViewsContext2D
  DEPENDS
    vtkIOExport
  PRIVATE_DEPENDS
    vtkCommonCore
    vtkImagingCore
    vtklibharu
)
