NAME
  VTK::IOOCCT
LIBRARY_NAME
  vtkIOOCCT
DESCRIPTION
  OCCT bridge for VTK, see README for more info
LICENSE_FILES
  LICENSE
SPDX_LICENSE_IDENTIFIER
  BSD-3-Clause
SPDX_COPYRIGHT_TEXT
  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
  Copyright 2019-2021 Kitware SAS
  Copyright 2021-2022 Michael Migliore, Mathieu Westphal
DEPENDS
  VTK::CommonExecutionModel
PRIVATE_DEPENDS
  VTK::CommonCore
  VTK::CommonDataModel
  VTK::FiltersGeneral
TEST_DEPENDS
  VTK::TestingCore
  VTK::TestingRendering
  VTK::RenderingOpenGL2
  VTK::InteractionStyle
