vtk_module(vtkFiltersFlowPaths
  GROUPS
    StandAlone
  DEPENDS
    vtkCommonExecutionModel
    vtkFiltersGeneral
    vtkFiltersSources
    vtkIOCore
  TEST_DEPENDS
    vtkFiltersAMR
    vtkFiltersImaging
    vtkTestingCore
    vtkTestingRendering
    vtkInteractionStyle
    vtkRendering${VTK_RENDERING_BACKEND}
  )
