vtk_module(vtkImagingColor
  GROUPS
    Imaging
    StandAlone
  TEST_DEPENDS
    vtkImagingCore
    vtkIOImage
    vtkTestingCore
  KIT
    vtkImaging
  DEPENDS
    vtkCommonExecutionModel
    vtkImagingCore
  PRIVATE_DEPENDS
    vtkCommonCore
    vtkCommonDataModel
    vtkCommonSystem
  )