vtk_module(vtkImagingColor
  GROUPS
    Imaging
    StandAlone
  KIT
    vtkImaging
  DEPENDS
    vtkCommonExecutionModel
    vtkImagingCore
  PRIVATE_DEPENDS
    vtkCommonCore
    vtkCommonDataModel
    vtkCommonSystem
  )