vtk_module(vtkIOGeometry
  GROUPS
    StandAlone
  DEPENDS
    vtkCommonDataModel
    vtkCommonSystem
    vtkCommonMisc
    vtkIOCore
    vtkzlib
  TEST_DEPENDS
    vtkIOAMR
    vtkFiltersGeometry
    vtkRenderingOpenGL
    vtkTestingRendering
  )
