NAME
  VTK::AcceleratorsVTKmCore
LIBRARY_NAME
  vtkAcceleratorsVTKmCore
DESCRIPTION
  VTKm data structures
SPDX_LICENSE_IDENTIFIER
  LicenseRef-BSD-3-Clause-Sandia-LANL-USGov
SPDX_COPYRIGHT_TEXT
  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
  Copyright (c) Kitware, Inc.
  Copyright 2015 Sandia Corporation.
  Copyright 2015 UT-Battelle, LLC.
  Copyright 2015 Los Alamos National Security.
SPDX_CUSTOM_LICENSE_FILE
  LICENSE
SPDX_CUSTOM_LICENSE_NAME
  BSD-3-Clause-Sandia-LANL-USGov
LICENSE_FILES
  LICENSE
DEPENDS
  VTK::CommonCore
  VTK::vtkvtkm
TEST_DEPENDS
  VTK::CommonSystem
  VTK::FiltersSources
  VTK::IOImage
  VTK::IOLegacy
  VTK::IOPLY
  VTK::IOXML
  VTK::ImagingHybrid
  VTK::ImagingSources
  VTK::InteractionStyle
  VTK::InteractionWidgets
  VTK::RenderingFreeType
  VTK::RenderingOpenGL2
  VTK::RenderingVolumeOpenGL2
  VTK::TestingCore
  VTK::TestingRendering
