NAME
  VTK::AcceleratorsVTKmCore
LIBRARY_NAME
  vtkAcceleratorsVTKmCore
DESCRIPTION
  Viskores (formerly VTK-m) data structures
SPDX_LICENSE_IDENTIFIER
  LicenseRef-BSD-3-Clause-Sandia-LANL-USGov
SPDX_COPYRIGHT_TEXT
  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
  Copyright (c) Kitware, Inc.
  Copyright 2015 Sandia Corporation.
  Copyright 2015 UT-Battelle, LLC.
  Copyright 2015 Los Alamos National Security.
SPDX_CUSTOM_LICENSE_FILE
  LICENSE
SPDX_CUSTOM_LICENSE_NAME
  BSD-3-Clause-Sandia-LANL-USGov
LICENSE_FILES
  LICENSE
DEPENDS
  VTK::CommonCore
  VTK::vtkviskores
TEST_DEPENDS
  VTK::ImagingCore
  VTK::CommonDataModel
  VTK::TestingCore
  VTK::TestingRendering
