vtk_module(vtkCommonColor
  TEST_DEPENDS
    vtkIOImage
    vtkCommonExecutionModel
    vtkRendering${VTK_RENDERING_BACKEND}
    vtkTestingCore
    vtkTestingRendering
    vtkInteractionStyle
  KIT
    vtkCommon
  DEPENDS
    vtkCommonCore
    vtkCommonDataModel
)