if (NOT VTK_LEGACY_REMOVE)
vtk_module(vtkInfovisParallel
  TEST_DEPENDS
    vtkViewsInfovis
    vtkInfovisLayout
    vtkIOMySQL
    vtkTestingRendering
  EXCLUDE_FROM_ALL
  DEPENDS
    vtkCommonCore
    vtkCommonDataModel
    vtkCommonExecutionModel
    vtkInfovisBoost
    vtkInfovisBoostGraphAlgorithms
  PRIVATE_DEPENDS
    vtkCommonSystem
    vtkFiltersExtraction
    vtkFiltersParallel
    vtkIOSQL
    vtkParallelMPI
  )
endif()