NAME
  VTK::IOHDF
LIBRARY_NAME
  vtkIOHDF
GROUPS
  StandAlone
SPDX_LICENSE_IDENTIFIER
  BSD-3-Clause
SPDX_COPYRIGHT_TEXT
  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
DEPENDS
  VTK::CommonCore
  VTK::CommonDataModel
  VTK::CommonExecutionModel
  VTK::FiltersCore
  VTK::IOCore
  VTK::IOHDFTools
PRIVATE_DEPENDS
  VTK::CommonSystem
  VTK::hdf5
  VTK::IOCore
  VTK::vtksys
  VTK::FiltersTemporal
  VTK::ParallelCore
TEST_DEPENDS
  VTK::FiltersGeneral
  VTK::FiltersHybrid
  VTK::FiltersParallelDIY2
  VTK::FiltersPoints
  VTK::FiltersSources
  VTK::FiltersTemporal
  VTK::hdf5
  VTK::ImagingCore
  VTK::IOGeometry
  VTK::IOXML
  VTK::TestingCore
  VTK::TestingRendering
  # We need vtkIOExodus as otherwise an information key will be missing, generating
  # the following warning:
  #   Could not locate key vtkExodusIIReader::GLOBAL_TEMPORAL_VARIABLE.
  VTK::IOExodus
TEST_OPTIONAL_DEPENDS
  VTK::FiltersParallelMPI
  VTK::mpi
  VTK::ParallelMPI
