NAME
  VTK::IOCatalystConduit
LIBRARY_NAME
  vtkIOCatalystConduit
DESCRIPTION
  Catalyst implementation for VTK, including Conduit to/from VTK conversion.
KIT
  VTK::IO
SPDX_LICENSE_IDENTIFIER
  BSD-3-Clause
SPDX_COPYRIGHT_TEXT
  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
DEPENDS
  VTK::CommonDataModel
  VTK::CommonExecutionModel
  VTK::ParallelCore
OPTIONAL_DEPENDS
  VTK::ParallelMPI
PRIVATE_DEPENDS
  VTK::FiltersCore
  VTK::FiltersAMR
TEST_DEPENDS
  VTK::TestingCore
  VTK::IOXML
