vtk_module(vtkWebCore
  GROUPS
    Web
  DEPENDS
    vtkCommonCore
  PRIVATE_DEPENDS
    vtksys
    vtkFiltersGeneral
    vtkPython
    vtkIOCore
    vtkIOImage
    vtkRenderingCore
    vtkParallelCore
    vtkWebGLExporter
  TEST_DEPENDS
    vtkImagingSources
    vtkTestingCore
  TEST_LABELS
    VTKWEB
  EXCLUDE_FROM_ALL
)
