NAME
  VTK::FiltersCellGrid
LIBRARY_NAME
  vtkFiltersCellGrid
DESCRIPTION
  Filters and cell-types for vtkCellGrid objects
KIT
  VTK::Filters
GROUPS
  StandAlone
SPDX_LICENSE_IDENTIFIER
  BSD-3-Clause
SPDX_COPYRIGHT_TEXT
  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
DEPENDS
  VTK::CommonCore
  VTK::CommonDataModel
  VTK::CommonExecutionModel
PRIVATE_DEPENDS
  VTK::FiltersCore
TEST_DEPENDS
  VTK::CommonSystem
  VTK::IOCellGrid
  VTK::TestingCore
