set SLICE_ORDER hfsi
set ROWS 470
set COLUMNS 500
set STUDY ../../../vtkdata/frog/frogTissue
set PIXEL_SIZE 1
set SPACING 1.5
set VALUE 127.5
set SAMPLE_RATE "1 1 1"
set GAUSSIAN_STANDARD_DEVIATION "2 2 2"
set DECIMATE_REDUCTION .95
set DECIMATE_ITERATIONS 5
set DECIMATE_ERROR .0002
set DECIMATE_ERROR_INCREMENT .0002
set SMOOTH_ITERATIONS 0
set SMOOTH_FACTOR .01
set FEATURE_ANGLE 60
