set opacity .4
[lungActor GetProperty] SetOpacity $opacity
[heartActor GetProperty] SetOpacity $opacity
[liverActor GetProperty] SetOpacity $opacity
[duodenumActor GetProperty] SetOpacity $opacity
[bloodActor GetProperty] SetOpacity $opacity
[brainActor GetProperty] SetOpacity $opacity
[eyeActor GetProperty] SetOpacity $opacity
[eye_retnaActor GetProperty] SetOpacity $opacity
[eye_whiteActor GetProperty] SetOpacity $opacity
[ileumActor GetProperty] SetOpacity $opacity
[kidneyActor GetProperty] SetOpacity $opacity
[l_intestineActor GetProperty] SetOpacity $opacity
[nerveActor GetProperty] SetOpacity $opacity
[spleenActor GetProperty] SetOpacity $opacity
[stomachActor GetProperty] SetOpacity $opacity
[skeletonActor GetProperty] SetOpacity $opacity
[muscleActor GetProperty] SetOpacity .2
[skinActor GetProperty] SetOpacity .3
