vtk_module(vtkIOVPIC
  TEST_DEPENDS
    vtkRenderingOpenGL2
    vtkTestingRendering
    vtkInteractionStyle
  KIT
    vtkParallel
  DEPENDS
    vtkCommonExecutionModel
    vtkvpic
  PRIVATE_DEPENDS
    vtkCommonCore
    vtkCommonDataModel
    vtkCommonMisc
    vtkParallelCore
  )
