vtk_module(vtkFiltersStatisticsGnuR
  IMPLEMENTS
    vtkFiltersStatistics
  DEPENDS
    vtkCommonCore
    vtkCommonExecutionModel
    vtkFiltersStatistics
  TEST_DEPENDS
    vtkTestingCore
    vtkFiltersSources
    vtkInfovisCore
  EXCLUDE_FROM_ALL)
