vtk_module(vtkFiltersStatisticsGnuR
  IMPLEMENTS
    vtkFiltersStatistics
  TEST_DEPENDS
    vtkTestingCore
    vtkFiltersSources
    vtkInfovisCore
  EXCLUDE_FROM_ALL
  KIT
    vtkFilters
  DEPENDS
    vtkCommonCore
    vtkCommonExecutionModel
    vtkFiltersStatistics
  PRIVATE_DEPENDS
    vtkCommonDataModel
    vtkCommonMisc
    vtksys
  )