NAME
  VTK::CommonMath
LIBRARY_NAME
  vtkCommonMath
DESCRIPTION
  Linear algebra types
KIT
  VTK::Common
GROUPS
  StandAlone
SPDX_LICENSE_IDENTIFIER
  LicenseRef-BSD-3-Clause-Sandia-USGov
SPDX_COPYRIGHT_TEXT
  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
  Copyright Sandia Corporation
SPDX_CUSTOM_LICENSE_FILE
  LICENSE
SPDX_CUSTOM_LICENSE_NAME
  BSD-3-Clause-Sandia-USGov
LICENSE_FILES
  LICENSE
DEPENDS
  VTK::CommonCore
  VTK::kissfft
TEST_DEPENDS
  VTK::CommonDataModel
  VTK::CommonSystem
  VTK::CommonTransforms
  VTK::TestingCore
INCLUDE_MARSHAL
