vtk_module(vtkInfovisLayout
  GROUPS
    StandAlone
  DEPENDS
    vtkCommonExecutionModel
    vtkImagingHybrid
    vtkFiltersModeling
    vtkInfovisCore
  TEST_DEPENDS
    vtkRenderingLabel
    vtkRenderingOpenGL2
    vtkTestingRendering
    vtkInteractionStyle
    vtkIOInfovis
  )
