VTK_WRAP_TCL3(vtk${KIT}TCL KitTCL_SRCS
  "${Kit_SRCS}"
  "${Kit_TCL_EXTRA_CMDS}")
ADD_LIBRARY(vtk${KIT}TCL ${KitTCL_SRCS} ${Kit_TCL_EXTRA_SRCS})
SET(KIT_LIBRARY_TARGETS ${KIT_LIBRARY_TARGETS} vtk${KIT}TCL)
TARGET_LINK_LIBRARIES (vtk${KIT}TCL vtk${KIT} ${KIT_TCL_LIBS})
IF(NOT VTK_INSTALL_NO_LIBRARIES)
  INSTALL_TARGETS(${VTK_INSTALL_LIB_DIR} vtk${KIT}TCL)
ENDIF(NOT VTK_INSTALL_NO_LIBRARIES)
IF(KIT_TCL_DEPS)
  ADD_DEPENDENCIES(vtk${KIT}TCL ${KIT_TCL_DEPS})
ENDIF(KIT_TCL_DEPS)

