VTK_WRAP_TCL3(vtk${KIT}TCL KitTCL_SRCS
  "${Kit_SRCS}"
  "${Kit_TCL_EXTRA_CMDS}")
VTK_ADD_LIBRARY(vtk${KIT}TCL ${KitTCL_SRCS} ${Kit_TCL_EXTRA_SRCS})
SET(KIT_LIBRARY_TARGETS ${KIT_LIBRARY_TARGETS} vtk${KIT}TCL)
TARGET_LINK_LIBRARIES (vtk${KIT}TCL vtk${KIT} ${KIT_TCL_LIBS})
IF(NOT VTK_INSTALL_NO_LIBRARIES)
  INSTALL(TARGETS vtk${KIT}TCL
    EXPORT ${VTK_INSTALL_EXPORT_NAME}
    RUNTIME DESTINATION ${VTK_INSTALL_BIN_DIR_CM24} COMPONENT RuntimeLibraries
    LIBRARY DESTINATION ${VTK_INSTALL_LIB_DIR_CM24} COMPONENT RuntimeLibraries
    ARCHIVE DESTINATION ${VTK_INSTALL_LIB_DIR_CM24} COMPONENT Development)
ENDIF(NOT VTK_INSTALL_NO_LIBRARIES)
ADD_DEPENDENCIES(vtk${KIT}TCL vtk${KIT})
IF(KIT_TCL_DEPS)
  ADD_DEPENDENCIES(vtk${KIT}TCL ${KIT_TCL_DEPS})
ENDIF(KIT_TCL_DEPS)

