#!/bin/sh
echo 'Please initialize your local Git hooks.
Paste the following commands into a shell:

 cd "'$PWD'/.git/hooks"
 git init
 git pull .. remotes/origin/hooks
 cd ../..

See http://www.vtk.org/Wiki/VTK/Git#Hooks for more details.'
exit 1
