NAME
  VTK::IOMotionFX
LIBRARY_NAME
  vtkIOMotionFX
CONDITION
  NOT CMAKE_CXX_COMPILER_ID STREQUAL "MSVC" OR CMAKE_CXX_COMPILER_VERSION VERSION_GREATER "18.0.0"
GROUPS
  StandAlone
SPDX_LICENSE_IDENTIFIER
  BSD-3-Clause
SPDX_COPYRIGHT_TEXT
  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
DEPENDS
  VTK::CommonExecutionModel
PRIVATE_DEPENDS
  VTK::CommonDataModel
  VTK::CommonMisc
  VTK::IOGeometry
  VTK::pegtl
  VTK::vtksys
TEST_DEPENDS
  VTK::InteractionStyle
  VTK::RenderingOpenGL2
  VTK::TestingCore
  VTK::TestingRendering
