NAME
  VTK::SerializationManager
LIBRARY_NAME
  vtkSerializationManager
DESCRIPTION
  Manage object serialization and deserialization utilities.
SPDX_LICENSE_IDENTIFIER
  BSD-3-Clause
SPDX_COPYRIGHT_TEXT
  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
DEPENDS
  VTK::CommonCore
  VTK::CommonDataModel
OPTIONAL_DEPENDS
  VTK::RenderingCore
TEST_DEPENDS
  VTK::FiltersCore
  VTK::ImagingCore
  VTK::InteractionStyle
  VTK::RenderingCore
  VTK::RenderingOpenGL2
  VTK::RenderingUI
  VTK::TestingCore
  VTK::TestingRendering
  VTK::TestingSerialization
