vtk_module(vtkParallelCore
  GROUPS
    StandAlone
  TEST_DEPENDS
    vtkTestingRendering
    vtkRenderingOpenGL2
  KIT
    vtkParallel
  DEPENDS
    vtkCommonCore
  PRIVATE_DEPENDS
    vtkCommonDataModel
    vtkCommonSystem
    vtkIOLegacy
    vtksys
  )
