vtk_module(vtkIOExport
  GROUPS
    StandAlone
  DEPENDS
    vtkCommonCore
    vtkMathText
    vtkRenderingContext2D
    vtkRenderingCore
    vtkRenderingFreeType
    vtkRenderingGL2PS
    vtkImagingCore
    vtkIOCore
  TEST_DEPENDS
    vtkChartsCore
    vtkInteractionImage
    vtkTestingRendering
    vtkRenderingAnnotation
    vtkRenderingOpenGL
    vtkRenderingFreeTypeOpenGL
    vtkRenderingVolumeOpenGL
    vtkViewsContext2D
  )
