vtk_module(vtkRenderingFreeTypeOpenGL
  GROUPS
    Rendering
  IMPLEMENTS
    vtkRenderingCore
  DEPENDS
    vtkRenderingFreeType
    vtkRendering${VTK_RENDERING_BACKEND}
  TEST_DEPENDS
    vtkTestingCore
    vtkTestingRendering
    vtkInteractionStyle
  )
