vtk_module(vtkRenderingHybridOpenGL
  GROUPS
    Rendering
  DEPENDS
    vtkIOLegacy
    vtkImagingSources
    vtkImagingHybrid
    vtkRenderingOpenGL
  TEST_DEPENDS
    vtkIOLegacy
    vtkIOXML
    vtkTestingCore
    vtkTestingRendering
    vtkInteractionStyle
  )
