vtk_module(vtkRenderingHybridOpenGL
  GROUPS
    Rendering
  DEPENDS
    vtkIOXML
    vtkIOLegacy
    vtkImagingSources
    vtkRenderingOpenGL
  PRIVATE_DEPENDS
    vtksys
  TEST_DEPENDS
    vtkIOXML
    vtkIOLegacy
    vtkTestingCore
    vtkTestingRendering
    vtkInteractionStyle
  )
