set(VTK_DIST_NAME_SUFFIX "egl" CACHE STRING "")
set(VTK_OPENGL_HAS_EGL ON CACHE BOOL "")
set(VTK_USE_X OFF CACHE BOOL "")

if ("$ENV{CMAKE_CONFIGURATION}" MATCHES "linux")
  set(CMAKE_PREFIX_PATH "/opt/mesa" CACHE PATH "")
endif ()
