set(CMAKE_C_COMPILER_LAUNCHER "sccache" CACHE STRING "")
set(CMAKE_CXX_COMPILER_LAUNCHER "sccache" CACHE STRING "")

if (VTK_USE_CUDA)
  set(CMAKE_CUDA_COMPILER_LAUNCHER "sccache" CACHE STRING "")
endif()
