radiobutton .case1 -text "Case 1" -value case1 -command "case1 Scalars 1 0; Grid Modified; renWin Render;"
radiobutton .case1c -text "Case 1 Complement" -value case1c -command "case1 Scalars 0 1; Grid Modified; renWin Render;"
radiobutton .case2 -text "Case 2" -value case2 -command "case2 Scalars 1 0; Grid Modified; renWin Render;"
radiobutton .case2c -text "Case 2 Complement" -value case2c -command "case2 Scalars 0 1; Grid Modified; renWin Render;"
radiobutton .case3 -text "Case 3" -value case3 -command "case3 Scalars 1 0; Grid Modified; renWin Render;"
radiobutton .case3c -text "Case 3 Complement" -value case3c -command "case3 Scalars 0 1; Grid Modified; renWin Render;"
radiobutton .case4 -text "Case 4" -value case4 -command "case4 Scalars 1 0; Grid Modified; renWin Render;"
radiobutton .case4c -text "Case 4 Complement" -value case4c -command "case4 Scalars 0 1; Grid Modified; renWin Render;"
radiobutton .case5 -text "Case 5" -value case5 -command "case5 Scalars 1 0; Grid Modified; renWin Render;"
radiobutton .case5c -text "Case 5 Complement" -value case5c -command "case5 Scalars 0 1; Grid Modified; renWin Render;"
radiobutton .case6 -text "Case 6" -value case6 -command "case6 Scalars 1 0; Grid Modified; renWin Render;"
radiobutton .case6c -text "Case 6 Complement" -value case6c -command "case6 Scalars 0 1; Grid Modified; renWin Render;"
radiobutton .case7 -text "Case 7" -value case7 -command "case7 Scalars 1 0; Grid Modified; renWin Render;"
radiobutton .case7c -text "Case 7 Complement" -value case7c -command "case7 Scalars 0 1; Grid Modified; renWin Render;"
radiobutton .case8 -text "Case 8" -value case8 -command "case8 Scalars 1 0; Grid Modified; renWin Render;"
radiobutton .case8c -text "Case 8 Complement" -value case8c -command "case8 Scalars 0 1; Grid Modified; renWin Render;"
radiobutton .case9 -text "Case 9" -value case9 -command "case9 Scalars 1 0; Grid Modified; renWin Render;"
radiobutton .case9c -text "Case 9 Complement" -value case9c -command "case9 Scalars 0 1; Grid Modified; renWin Render;"
radiobutton .case10 -text "Case 10" -value case10 -command "case10 Scalars 1 0; Grid Modified; renWin Render;"
radiobutton .case10c -text "Case 10 Complement" -value case10c -command "case10 Scalars 0 1; Grid Modified; renWin Render;"
radiobutton .case11 -text "Case 11" -value case11 -command "case11 Scalars 1 0; Grid Modified; renWin Render;"
radiobutton .case11c -text "Case 11 Complement" -value case11c -command "case11 Scalars 0 1; Grid Modified; renWin Render;"
radiobutton .case12 -text "Case 12" -value case12 -command "case12 Scalars 1 0; Grid Modified; renWin Render;"
radiobutton .case12c -text "Case 12 Complement" -value case12c -command "case12 Scalars 0 1; Grid Modified; renWin Render;"
radiobutton .case13 -text "Case 13" -value case13 -command "case13 Scalars 1 0; Grid Modified; renWin Render;"
radiobutton .case13c -text "Case 13 Complement" -value case13c -command "case13 Scalars 0 1; Grid Modified; renWin Render;"
radiobutton .case14 -text "Case 14" -value case14 -command "case14 Scalars 1 0; Grid Modified; renWin Render;"
radiobutton .case14c -text "Case 14 Complement" -value case14c -command "case14 Scalars 0 1; Grid Modified; renWin Render;"
pack .case1 .case1c .case2 .case2c .case3 .case3c .case4 .case4c .case5 .case5c .case6 .case6c .case7 .case7c .case8 .case8c .case9 .case9c .case10 .case10c .case11 .case11c .case12 .case12c .case13 .case13c .case14 .case14c


