unset(__priv_deps)
if("${VTK_RENDERING_BACKEND}" STREQUAL "OpenGL2")
  list(APPEND __priv_deps vtkglew)
endif()
vtk_module(vtkRenderingParallel
  TEST_DEPENDS
    vtkParallelMPI
    vtkFiltersParallelMPI
    vtkTestingRendering
    vtkImagingSources
    vtkRendering${VTK_RENDERING_BACKEND}
    vtkInteractionStyle
    vtkTestingCore
  KIT
    vtkParallel
  DEPENDS
    vtkCommonCore
    vtkRendering${VTK_RENDERING_BACKEND}
    vtkRenderingCore
  PRIVATE_DEPENDS
    ${__priv_deps}
    vtkCommonDataModel
    vtkCommonMath
    vtkCommonSystem
    vtkFiltersParallel
    vtkIOImage
    vtkImagingCore
    vtkParallelCore
  )